#10050 - Remove case from external message when deleting
hzi-braunschweig/SORMAS-Project pull request #10057
Opened 2022-08-05 12:29 UTC by MateStrysewske

Fixes #10050

2022-08-05 12:56 UTC, leventegal-she approved these changes

2022-08-05 12:58 UTC, leventegal-she requested changes
The case field in ExternalMessageCriteria is not handled in ExternalMessageService::buildCriteriaFilter

2022-08-08 11:11 UTC, leventegal-she approved these changes

2022-08-08 13:15 UTC, merged

2022-08-10 08:59 UTC, FredrikSchaeferVitagroup commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +		externalMessageService.getForCase(new CaseReferenceDto(caze.getUuid())).forEach(labMessage -> {
There is a small naming issue with this. 
SORMAS has external messages now, which can be of type lab message or physician's report. Actually, external messages with a case reference are always phisycan's reports, never lab messages. Thus, the parameter name labMessage is misleading here. @MateStrysewske Shall I just push a small fix of this (tagging #10050) to development?