#9755 s2 s share requests directory
hzi-braunschweig/SORMAS-Project pull request #10161
Opened 2022-08-18 11:49 UTC by leventegal-she

Fixes #9755

2022-08-22 12:03 UTC, JonasCir requested changes
![change_buttons](https://user-images.githubusercontent.com/20031875/185916774-261cb00e-0d67-401d-915d-38b232bc9411.png)
![details_with](https://user-images.githubusercontent.com/20031875/185916779-ef25bb42-ac05-4aa1-bb48-a184f24a6deb.png)
![revoke_button](https://user-images.githubusercontent.com/20031875/185916784-efd198a2-96b8-41e8-9a05-ad058fc83ac3.png)
![share_width](https://user-images.githubusercontent.com/20031875/185916785-ba169623-1b7c-4134-8a21-7aeb881b512d.png)

2022-08-24 09:46 UTC, leventegal-she commented
> Please switch the buttons here. The reason is that users will more frequently select something and then apply it then revoke it. 

The order of the buttons are set in a base class so it is the same for all pages and I didn't see any complaints from SORMAS users to change it. So I would say it is ok.

> The address field is cut

You should scroll to right to see the address and other columns

> Please move the buttons at the end of the line after the comment. 

It is requested in the ticket that the comment is the last column

> The first column is cut although there is enough space

I will remove the caption of that column because it is not needed

2022-08-24 09:47 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/ShareRequestGrid.java
> +			COLUMN_ACTIONS,
It is requested in the ticket that the comment is the last column

2022-08-29 11:27 UTC, JonasCir commented
@leventegal-she I'm not certain, are you still working on this? Are you going to address the inline comments from my last review? :)

2022-08-29 11:46 UTC, leventegal-she commented
> you going to address the inline comments from my la

I changed as you  suggested

2022-08-29 11:58 UTC, JonasCir commented
Ok I was confused as the comments were not resolved, my bad :) Good to go!

2022-08-29 11:58 UTC, JonasCir approved these changes

2022-08-29 11:59 UTC, merged