Qu auto/sorqa 366
hzi-braunschweig/SORMAS-Project pull request #10183
Opened 2022-08-23 07:32 UTC by lb-sgent

<img width="671" alt="image" src="https://user-images.githubusercontent.com/105343291/186098526-6d912c32-027e-410a-af32-115f46962b01.png">

2022-08-23 10:22 UTC, mp-sgent approved these changes

2022-08-23 10:41 UTC, pk-sgent approved these changes

2022-08-23 11:32 UTC, rdutu-vg requested changes

2022-08-23 11:32 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseImportExportSteps.java
> +            String file = "./downloads/sormas_fälle_" + LocalDate.now().format(formatter) +
replace all this by using from FilesHelper class

2022-08-23 11:32 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseImportExportSteps.java
> +        "I add ([^\"]*) data to export in existing Export Configuration for Custom Case Export",
let' replace add with select, since the method since the method is selecting something from UI

2022-08-23 11:32 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseImportExportSteps.java
> +        "I save Custom Export Configuration",
rename it with the action performed in UI,  "I click on Save button from {page location}"

2022-08-23 11:32 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/resources/features/sanity/web/CaseImportExport.feature
> +
remove extra spaces

2022-08-25 07:27 UTC, rdutu-vg approved these changes

2022-08-25 07:27 UTC, merged