#8543 Add backend checks to access documents
hzi-braunschweig/SORMAS-Project pull request #10281
Opened 2022-09-05 13:26 UTC by leventegal-she

Fixes #8543

2022-09-06 10:00 UTC, ChristopherRiedel requested changes

2022-09-08 06:59 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/document/DocumentStorageService.java
>  	}
It doesn't work on Mac but I've reverted it now

2022-09-08 07:36 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/document/DocumentStorageService.java
>  	}
This means setAttribute is not work on Mac in general or is it something specific that would make sense to fix?

2022-09-08 07:37 UTC, MartinWahnschaffe commented
Apart from the existing comments, it looks very good to me.

2022-09-08 08:03 UTC, ChristopherRiedel approved these changes

2022-09-08 08:15 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/document/DocumentStorageService.java
>  	}
Looks like JDK was not supporting user defined file attributes on OS X.
It was finally implemented with Java 17 (!): https://bugs.openjdk.org/browse/JDK-8030048

I'd suggest to add a try catch block into the setAttribute method for UnsupportedOperationException

2022-09-08 13:50 UTC, merged