Feature/9091 stats access right
hzi-braunschweig/SORMAS-Project pull request #10291
Opened 2022-09-06 14:35 UTC by JonasCir

Fixes #9091

2022-09-06 14:38 UTC, JonasCir commented on sormas-base/setup/keycloak/SORMAS.json
> -            "multivalued": "true"
Check `multivalued` again

2022-09-16 11:37 UTC, MartinWahnschaffe requested changes
Other than my comments, LGTM.
@JonasCir Would like to go though the keycloak parts with you and also discuss how this is tested by QA.

2022-09-20 08:37 UTC, JonasCir commented on sormas-base/setup/keycloak/README.md
> +# SORMAS Keycloak integration
done

2022-09-20 08:38 UTC, JonasCir commented
@MartinWahnschaffe review addressed :)

2022-09-20 13:03 UTC, merged