#10218_warning_message_not_displayed added a warning message when use…
hzi-braunschweig/SORMAS-Project pull request #10374
Opened 2022-09-15 12:20 UTC by valentinmikleuvg

…r click on Bulk Actions -> Create Contacts with no event participant selected

Fixes #

2022-09-15 12:24 UTC, StefanKock reviewed
The commit message does not contain the ticket id.

Rewrite the commit message to:
```
#10218 added a warning message when user click on Bulk Actions

-> Create Contacts with no event participant selected`
```

2022-09-15 12:25 UTC, StefanKock requested changes
commit message not appropriate

2022-09-16 14:22 UTC, carina29 approved these changes

2022-09-19 06:38 UTC, StefanKock commented on sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
> +		if (eventParticipantIndexDtos.size() == 0) {
This is not null-safe anymore. Let's hope no one calls this with `null`

2022-09-19 06:38 UTC, StefanKock commented on sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactController.java
> +			new Notification(
The whole message block could have been added to the pre-existing if clause without adding an else statement.

2022-09-19 06:39 UTC, StefanKock reviewed
Added some remarks but my initial request was fixed

2022-09-19 06:39 UTC, StefanKock approved these changes

2022-09-19 15:40 UTC, merged