Bugfix 10343 missing validations via api
hzi-braunschweig/SORMAS-Project pull request #10383
Opened 2022-09-17 13:08 UTC by andrei7bal

#10343 Add new validations for required fields when adding data from API
- add new validations for Sample and for TravelEntry
- use @NotEmpty annotation instead of @Requried (it's gonna be deprecated)

2022-09-19 07:59 UTC, JonasCir requested changes
Hey,
1. `NotEmpty` makes only sense on Strings, not other Objects. Therefore, use `NotNull`
2. I made a mistake: On Strings (if any use `NotBlank`, NOT `NotEmpty`
3. CI has a test failure

2022-09-21 14:23 UTC, andrei7bal commented
Hello @JonasCir 
I've commited the changes. Please note that for the @Required annotation refactoring, there will be a new ticket (as I was suggested), so for this Pull Request only PointOfEntryDetails (TravelEntryDto) and SampleMaterialText (SampleDto) are treated.
Thanks for looking into this.

2022-09-21 14:35 UTC, JonasCir commented on sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
> +	String validPointOfEntryDetails = "validPointOfEntryDetails";
remove this

2022-09-21 14:35 UTC, JonasCir commented on sormas-api/src/main/java/de/symeda/sormas/api/i18n/Validations.java
> +	String validSampleMaterialText = "validSampleMaterialText";
remove this

2022-09-21 14:35 UTC, JonasCir commented on sormas-api/src/main/java/de/symeda/sormas/api/sample/SampleDto.java
> +	@NotBlank(message = Validations.validSampleMaterialText)
should be `@NotBlank(message = Validations.requiredField)`

2022-09-21 14:36 UTC, JonasCir commented on sormas-api/src/main/java/de/symeda/sormas/api/travelentry/TravelEntryDto.java
> +	@NotBlank(message = Validations.validPointOfEntryDetails)
should be `@NotBlank(message = Validations.requiredField)`

2022-09-22 13:02 UTC, JonasCir commented
hey, take a look at the issue again: The second scenario is not fixed.

2022-09-22 14:07 UTC, JonasCir commented
tests are failing now

2022-09-29 09:38 UTC, merged