Change 9109 process multiple samples via one message
hzi-braunschweig/SORMAS-Project pull request #10455
Opened 2022-09-27 09:02 UTC by FredrikSchaeferVitagroup

Fixes #9109

2022-09-28 08:49 UTC, leventegal-she requested changes

2022-09-28 08:49 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/labmessage/processing/AbstractLabMessageProcessingFlow.java
> +				currentFlow == null ? flow : currentFlow,
You can initialize `currentFlow` to be `flow` and than the ternary will not be needed

2022-09-28 08:57 UTC, FredrikSchaeferVitagroup commented on sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java
> +	public List<SampleReportDto> getSampleReportsNullSave() {
Agreed. I did't know that.

2022-09-29 06:47 UTC, FredrikSchaeferVitagroup commented on sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageDto.java
> +			SampleReportDto sampleReport = SampleReportDto.build();
In a discussion, it was decided not to implemet this idea. There is a mutual relation approach used here, and setting the one relation (sample report -> reference to labmessage) in the SampleReportDto.build(...) would leave the other relation (labmessage -> posession of sample report) to be done later. That is easy to overlook.

2022-09-29 08:27 UTC, leventegal-she approved these changes

2022-09-29 08:29 UTC, merged