#9852 Events participants created as archived
hzi-braunschweig/SORMAS-Project pull request #10498
Opened 2022-09-30 09:59 UTC by andrei7bal

#9852 Event participants newly created for archived events are archived too

2022-10-04 07:59 UTC, StefanKock requested changes

2022-10-04 07:59 UTC, StefanKock commented on sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjb.java
> +			entity.setArchived(event.isArchived());
The change should be done before `service.ensurePersisted`, maybe within `fillOrBuildEntity` or directly afterwards.

2022-10-04 07:59 UTC, StefanKock commented on sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
> +	{
Code formatting violated: Use Code formatting to move `{` after the method declaration

2022-10-04 07:59 UTC, StefanKock commented on sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
> +	public void testCreationOfExistingEventParticipantRemainsArchived()
This test is almost identical with the first test case. Please join both test cases (saves several seconds for unit test setup), and add code comments before each block to explain what that test step is testing. Example:

```java
// Verify that dearchiving of the event does not dearchive the event participant
```

2022-10-04 07:59 UTC, StefanKock commented on sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
> +	public void testCreationOfEventParticipantWhenArchived()
Please rename unit test to `testSaveEventParticipantWithEventArchiving`

2022-10-04 10:12 UTC, MateStrysewske requested changes
The change done in this PR is not acceptable. We can't set the archived status of event participants to the archived status of events all the time. There's the very likely scenario of an active event with some active and some archived event participants; editing one of the archived event participants retrospectively must NOT change their status back to active.

As discussed before, please ensure that:
- There's code in the logic that archives/de-archives an event that archives/de-archives all its event participants in the same process.
- Make sure that when saving an event participant for an ARCHIVED event, it's always archived.

2022-10-05 13:10 UTC, MateStrysewske approved these changes

2022-10-07 07:28 UTC, StefanKock requested changes
Only a finding on a curious test, the relevant changes look good

2022-10-07 07:28 UTC, StefanKock commented on sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java
> +		//Validate that for an already existing Event Participant the previous status is kept
This test description does not match: Creating a new event participant does not relate to what happened to the `archivedEventParticipantDto`

The last `assertEquals(getEventParticipantFacade().isArchived(archivedEventParticipantDto.getUuid()), getEventParticipantFacade().isArchived(alreadyArchivedParticipantDto.getUuid()));` does not check the expected behaviour but only if two values in the database are the same (but not if true or false).

2022-10-10 09:22 UTC, StefanKock approved these changes

2022-10-10 09:24 UTC, merged