#10414 limit persons by config and user rights
hzi-braunschweig/SORMAS-Project pull request #10502
Opened 2022-09-30 14:00 UTC by StefanKock

Fixes #10414

2022-10-05 07:59 UTC, MartinWahnschaffe requested changes

2022-10-05 07:59 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
> +				// NOOP: check the explicit associations
Same here

2022-10-05 07:59 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
> +			throw new IllegalArgumentException("No filter compiled for persons by association " + personAssociation.name());
Instead of throwing an exception return a "false" predicate.
This will likely also solve the external visit problems.

2022-10-05 07:59 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonService.java
> +			throw new IllegalArgumentException("No filter compiled for persons by associations: " + permittedAssociations);
Same here.

2022-10-25 14:22 UTC, MateStrysewske commented
@StefanKock Code looks good to me, would also do some testing after you've removed the Draft status from this PR (I suspect there will be merge conflicts that need to be taken care of first).

2022-10-25 15:15 UTC, MartinWahnschaffe approved these changes

2022-10-25 15:25 UTC, MartinWahnschaffe commented
@MateStrysewske doesn't seem to have any merge conflicts.

2022-10-26 07:38 UTC, MateStrysewske approved these changes

2022-11-02 15:30 UTC, merged