#9527 [S2S] Add a duplicate detection warning when sharing a case wit…
hzi-braunschweig/SORMAS-Project pull request #10539
Opened 2022-10-05 07:12 UTC by leventegal-she

…h another instance

Fixes #9527

2022-10-06 13:02 UTC, JonasCir requested changes

2022-10-06 14:03 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
> +	private Predicate getSimilarityFilters(
I don't know what would be a the best place for this, this is just a part of the `getMatchingContacts` method, extracted into e separate method to be reusable. For cases the corresponding method was in the service that's why `getSimilarityFilters` was created there

2022-10-06 14:29 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
> +						// TODO - filter
removed todo, and created a ticket https://github.com/hzi-braunschweig/SORMAS-Project/issues/10569 as suggested in https://github.com/hzi-braunschweig/SORMAS-Project/issues/9527#issuecomment-1268008512

2022-10-10 07:12 UTC, JonasCir commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
> +	private Predicate getSimilarityFilters(
fine with me

2022-10-10 07:12 UTC, JonasCir commented on sormas-ui/src/main/java/de/symeda/sormas/ui/sormastosormas/SormasToSormasController.java
> +						// TODO - filter
thx

2022-10-10 07:12 UTC, JonasCir approved these changes
lgtm

2022-10-10 10:29 UTC, merged