#8463 - Users with read permission should be able to see more details…
hzi-braunschweig/SORMAS-Project pull request #10845
Opened 2022-11-05 12:42 UTC by sergiupacurariu

… (Side-components)

Fixes #8463

2022-11-07 09:46 UTC, BarnaBartha requested changes

2022-11-07 09:46 UTC, BarnaBartha commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditAllowedDetailView.java
> +//				Field<?> field = root.getWrappedComponent().getFieldGroup().getField(propertyId);
please remove commented code

2022-11-07 12:34 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditAllowedDetailView.java
> +//				Field<?> field = root.getWrappedComponent().getFieldGroup().getField(propertyId);
removed

2022-11-08 07:52 UTC, BarnaBartha approved these changes

2022-11-08 07:53 UTC, merged