#10803 reinfection related checkboxes on case page remain unchecked
hzi-braunschweig/SORMAS-Project pull request #11006
Opened 2022-11-24 11:00 UTC by valentinmikleuvg

The checkboxes associated with reinfection are cleared only if the user save the changes made.

Fixes #10803

2022-11-25 13:33 UTC, carina29 requested changes

2022-11-25 13:33 UTC, carina29 commented on sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java
> +		if (cazeDto.getReInfection() == YesNoUnknown.NO || cazeDto.getReInfection() == YesNoUnknown.UNKNOWN) {
Can be checked directly if cazeDto.getReInfection() != YesNoUnknown.Yes instead of the above 2 conditions

2022-11-25 13:41 UTC, carina29 commented
I also tested the PR and everything works as it was requested :) After solving the added comment, we can merge it :)

2022-11-25 13:59 UTC, carina29 approved these changes

2022-11-25 14:00 UTC, merged

2022-11-28 09:10 UTC, StefanKock commented
The ticket was not linked in the commit, that's against the rules (it's already merged, so too late).

2022-11-28 09:21 UTC, carina29 commented
@StefanKock  Ah yes, good point I did not see it till now.
@valentinmikleuvg You have to add the number of the ticket in the commit message too 
![image](https://user-images.githubusercontent.com/47103965/204240323-f957fc28-f4f9-4080-acbd-96a1d519c641.png)

2022-11-28 09:24 UTC, StefanKock commented
For next time

2022-11-29 12:25 UTC, valentinmikleuvg commented
Sorry for this, I will link the ticket next time