#10247 S2S Surveillance Reports should be shareable (along with possibly attached External Messages)
hzi-braunschweig/SORMAS-Project pull request #11147
Opened 2022-12-09 11:48 UTC by leventegal-she

Fixes #10247

2022-12-15 12:20 UTC, JonasCir requested changes
Nicely done! 
1. One inline comment
2. Please add a test to `InfraValidationSoundnessTest` similar to `testShareLabMessageValidation`
3. PR needs rebase
4. I assume this should only merged for the next release I guess?

2022-12-16 16:23 UTC, leventegal-she commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/surveillancereport/SurveillanceReportDto.java
> +	public static SurveillanceReportDto build(CaseReferenceDto caze, UserReferenceDto reportingUser) {
There is no clear default value for those fields, it's better to let the user set theses values.

For example the reporting date on case is required but the re sui no `CaseDataDto::build` function that sets it.

2022-12-16 16:35 UTC, leventegal-she commented
> Nicely done!
> 
> 1. One inline comment
> 2. Please add a test to `InfraValidationSoundnessTest` similar to `testShareLabMessageValidation`
> 3. PR needs rebase
> 4. I assume this should only merged for the next release I guess?

1. Responded on the message
2. Done. Can you please add a comment on the test class so me and others would see what those tests do
3. Done
4. Yes, it's for 1.79

2022-12-19 09:29 UTC, JonasCir commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/surveillancereport/SurveillanceReportDto.java
> +	public static SurveillanceReportDto build(CaseReferenceDto caze, UserReferenceDto reportingUser) {
ok thanks

2022-12-19 09:35 UTC, JonasCir approved these changes
lgtm, I'm going to add a comment to the test classes later

2023-01-09 08:23 UTC, merged