Change/10251 clean non atomic endpoints
hzi-braunschweig/SORMAS-Project pull request #11159
Opened 2022-12-12 12:41 UTC by JonasCir

Fixes #10251

2023-03-14 14:11 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11159

2023-03-16 08:56 UTC, MartinWahnschaffe commented
**DON'T MERGE THIS, AS LONG AS THE NEEDED CHANGES IN SORMAS-APP AREN'T DONE.**

2023-03-17 12:30 UTC, ChristopherRiedel requested changes
Looks very good apart from the year numbers.

2023-03-17 12:30 UTC, ChristopherRiedel commented on sormas-rest/src/main/java/de/symeda/sormas/rest/exception/mappers/ConstraintViolationExceptionMapper.java
> + * Copyright © 2016-2022 Helmholtz-Zentrum für Infektionsforschung GmbH (HZI)
If the year is already adjusted it should be consistently 2023. This is only an example, please change completely for all touched classes.

2023-03-22 07:01 UTC, ChristopherRiedel approved these changes

2023-04-06 08:59 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11159

2023-04-06 12:14 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11159

2023-04-13 09:44 UTC, ChristopherRiedel approved these changes
I have now tested a lot and could not find any problems.

2023-04-14 07:16 UTC, MartinWahnschaffe commented
Thanks. I need to discuss the issue with QA before merging this. Realised it may affect our automatic tests.

2023-04-14 09:24 UTC, merged