Change 11002 reuse joins
hzi-braunschweig/SORMAS-Project pull request #11242
Opened 2022-12-22 08:04 UTC by BarnaBartha

Fixes #11002

2022-12-22 09:01 UTC, StefanKock requested changes
Some code formatting remarks, but otherwise this looks good.

2022-12-22 13:34 UTC, BarnaBartha commented
@StefanKock unfortunately there are some tests i didn't get to fix, if i don't get the chance to do it next year please assign it to somebody else. thanks

2022-12-23 06:54 UTC, StefanKock commented
Failing tests (all `StackOverflowError`):
```
ImmunizationFacadeEjbTest.testGetAllSince:170 » Interceptor java.lang.StackOve...
ImmunizationFacadeEjbTest.testImmunizationAutomation:426 » Interceptor java.la...
ImmunizationFacadeEjbTest.testImmunizationCreatedByDistrictUserIsVisibleToThatUser:291 » Interceptor
ImmunizationFacadeEjbTest.testJurisdictionFiltering:254 » Interceptor java.lan...
PersonFacadeEjbPseudonymizationTest.testPseudonymizeGetAllAfter:370 » Interceptor
PersonFacadeEjbTest.testGetPersonsAfter:678 » Interceptor java.lang.StackOverf...
```

2022-12-23 12:24 UTC, StefanKock approved these changes
Fixed recursion, looked around that the pattern isn't somewhere else in the changed entity services

2022-12-23 12:34 UTC, merged