Change 10461 limit bulk action load
hzi-braunschweig/SORMAS-Project pull request #11442
Opened 2023-02-06 10:31 UTC by MateStrysewske

Fixes #10461

2023-02-07 14:36 UTC, sormas-vitagroup commented
SonarCloud analysis: Please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11442

2023-02-09 14:03 UTC, sergiupacurariu requested changes

2023-02-09 14:03 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
> +			return false;
same as for cases and events

2023-02-10 12:44 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11442

2023-02-14 07:39 UTC, sergiupacurariu requested changes

2023-02-15 13:46 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11442

2023-02-22 07:46 UTC, sergiupacurariu approved these changes

2023-02-22 07:47 UTC, merged