#11014 Two step getIndexList for other entities
hzi-braunschweig/SORMAS-Project pull request #11455
Opened 2023-02-07 12:45 UTC by leventegal-she

Fixes #11014

2023-02-07 18:10 UTC, sormas-vitagroup commented
SonarCloud analysis: Please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11455

2023-02-08 12:32 UTC, MateStrysewske requested changes

2023-02-08 12:32 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java
> +
I think there's a distinct missing here

2023-02-08 12:32 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventGroupFacadeEjb.java
> +
Distinct missing here as well

2023-02-08 12:32 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjb.java
> +
See above

2023-02-08 12:32 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleService.java
> +
See above

2023-02-08 12:32 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java
> +
See above

2023-02-08 13:13 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/action/ActionService.java
> +
That's true

2023-02-08 16:56 UTC, sormas-vitagroup commented
SonarCloud analysis: Please find the results at https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11455

2023-02-09 09:46 UTC, MateStrysewske approved these changes

2023-02-09 09:46 UTC, merged