#11544 - Error received at merge duplicate case
hzi-braunschweig/SORMAS-Project pull request #11562
Opened 2023-02-28 16:30 UTC by sergiupacurariu

Fixes #11544

2023-02-28 17:32 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11562

2023-03-01 08:20 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11562

2023-03-02 08:40 UTC, MateStrysewske requested changes
Had a discussion with @MartinWahnschaffe and we agreed that the solution here is kinda problematic because `AbstractUuidDto` should not have any additional fields.

Our proposed solution would be to instead override the equals and hashCode methods in CaseMergeIndexDto to work like Object.equals and Object.hashCode (i.e. only compare whether the two objects are the same and ignore the UUID); that should hopefully have the same effect.

Also, please add a class comment to CaseMergeIndexDto which explains that and why these methods need to be overridden.

2023-03-06 08:22 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11562

2023-03-06 11:03 UTC, MateStrysewske requested changes

2023-03-06 11:03 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/uuid/AbstractUuidDto.java
> +	protected String getUniqueUuid() {
Remove this field

2023-03-06 12:26 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11562

2023-03-06 12:39 UTC, sergiupacurariu commented on sormas-api/src/main/java/de/symeda/sormas/api/uuid/AbstractUuidDto.java
> +	protected String getUniqueUuid() {
removed

2023-03-06 13:02 UTC, MateStrysewske approved these changes

2023-03-06 13:02 UTC, merged