#10298 fix relevance status filter on the event participants list
hzi-braunschweig/SORMAS-Project pull request #11624
Opened 2023-03-10 15:46 UTC by leventegal-she

Fixes #10298

2023-03-10 16:19 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11624

2023-03-14 10:53 UTC, MateStrysewske requested changes
Status is still reset when trying to change it on an archived event

2023-03-14 15:29 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11624

2023-03-15 11:51 UTC, MateStrysewske approved these changes

2023-03-15 11:51 UTC, merged