[hzi-braunschweig/SORMAS-Security/issues/52] loadOtherCertificate mus…
hzi-braunschweig/SORMAS-Project pull request #11741
Opened 2023-03-27 10:15 UTC by JonasCir

…t check CN

Fixes https://github.com/hzi-braunschweig/SORMAS-Security/issues/52

I cannot test it currently as my setup broke recently

2023-03-27 10:50 UTC, leventegal-she requested changes
SormasToSormas tests are failing

2023-03-27 14:39 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11741

2023-04-05 14:03 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11741

2023-04-05 14:18 UTC, leventegal-she approved these changes

2023-04-05 14:18 UTC, merged