#3428 - fix UI stylings for Event Actions
hzi-braunschweig/SORMAS-Project pull request #11761
Opened 2023-03-29 14:24 UTC by carina29

Fixes #3428

2023-03-31 07:36 UTC, MateStrysewske requested changes
Please:
- Reduce the horizontal spacing between the icon and the action title a bit; maybe to HSPACE_LEFT_3 (unless that's TOO narrow)
- Align the edit icon with the action title vertically (right now it's displayed farther to the bottom which looks off)

2023-03-31 14:07 UTC, carina29 commented
@MateStrysewske I've corrected the points you've mentioned :) :
1) The problem was that the spacing on the layout was not set to false and the extra spacing added was too much ( now the extra spacing is set to false and I've added only the spacing you've suggested - CssStyles.HSPACE_LEFT_3)
2) The problem was that the title and the edit icon had different margin - top settings. Now for both we have a margin-top:12px set by CssStyle.H3 (in case of the title) and CssStyles.LABEL_HEADING_TITLE (in case of edit icon).

After the changes, the Page looks like this:
![image](https://user-images.githubusercontent.com/47103965/229143129-ee568e32-6a9b-4652-8473-c12f02163ce2.png)

Please let me know if I should do some further changes :)

2023-03-31 14:37 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11761

2023-04-03 09:39 UTC, MateStrysewske approved these changes

2023-04-03 09:39 UTC, merged