fixed #11793
hzi-braunschweig/SORMAS-Project pull request #11798
Opened 2023-04-05 11:53 UTC by ChristopherRiedel

Fixes #11793

2023-04-05 12:19 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11798

2023-04-06 14:30 UTC, sergiupacurariu requested changes

2023-04-12 15:14 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11798

2023-04-13 14:54 UTC, sergiupacurariu approved these changes

2023-04-13 14:54 UTC, merged