#11327 - Introduce bulk action 'Undo Deletion'
hzi-braunschweig/SORMAS-Project pull request #11802
Opened 2023-04-06 11:52 UTC by sergiupacurariu

Fixes #11327

2023-04-06 12:28 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11802

2023-04-11 07:58 UTC, MateStrysewske requested changes

2023-04-11 07:58 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +messageCaseSavedClassificationChanged = Case saved. The c  lassification was automatically changed to %s.
Revert this change

2023-04-11 07:58 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +messageCasesNotRestored = The cases mentioned in the above ids list could not be restored.
```suggestion
messageCasesNotRestored = The cases mentioned in the above list of UUIDs could not be restored.
```

2023-04-11 07:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteUndeleController.java
> +public class DeleteUndeleController<F extends DeletableFacade> {
```suggestion
public class DeleteUndeleteController<F extends DeletableFacade> {
```

2023-04-11 07:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryController.java
> +	public void undeleteSelectedCases(Collection<? extends TravelEntryIndexDto> selectedRows, Runnable callback) {
```suggestion
	public void undeleteSelectedTravelEntries(Collection<? extends TravelEntryIndexDto> selectedRows, Runnable callback) {
```

2023-04-11 07:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteUndeleController.java
> +			int countNotRestoredCases = 0;
```suggestion
			int countNotRestoredEntities = 0;
```

2023-04-11 07:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteUndeleController.java
> +			StringBuilder notRestoredCases = new StringBuilder();
```suggestion
			StringBuilder notRestoredEntities = new StringBuilder();
```

2023-04-11 08:16 UTC, sergiupacurariu commented on sormas-api/src/main/resources/strings.properties
> +messageCaseSavedClassificationChanged = Case saved. The c  lassification was automatically changed to %s.
reverted

2023-04-11 08:17 UTC, sergiupacurariu commented on sormas-api/src/main/resources/strings.properties
> +messageCasesNotRestored = The cases mentioned in the above ids list could not be restored.
updated

2023-04-11 08:20 UTC, sergiupacurariu commented on sormas-api/src/main/resources/strings.properties
> +messageCountCasesNotRestored = %s cases not restored. CasesIds not restored: %s
changed

2023-04-11 08:20 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteUndeleController.java
> +public class DeleteUndeleController<F extends DeletableFacade> {
updated

2023-04-11 08:21 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryController.java
> +	public void undeleteSelectedCases(Collection<? extends TravelEntryIndexDto> selectedRows, Runnable callback) {
changed

2023-04-11 08:22 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteUndeleController.java
> +		if (entityUuids.size() == 0) {
changed

2023-04-11 08:23 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteUndeleController.java
> +			StringBuilder notRestoredCases = new StringBuilder();
changed

2023-04-11 08:25 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11802

2023-04-11 08:56 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11802

2023-04-12 10:33 UTC, MateStrysewske requested changes
- The confirmation pop-up when undeleting entities does not appear; the undeletion is done immediately
- The success notification is only displayed for a very short amount of time when the user moves their mouse because of the chosen notification type (it's basically not readable); use the tray notification instead

2023-04-13 14:13 UTC, sergiupacurariu commented
issues regarding pop-up confirmation and tray notification have been fixed

2023-04-14 08:14 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11802

2023-04-14 09:32 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11802

2023-04-14 09:39 UTC, merged