#11854: Refactored all code occurrences of "Undelete" to "Restore"
hzi-braunschweig/SORMAS-Project pull request #11855
Opened 2023-04-14 11:54 UTC by ChristopherRiedel

Fixes #11854

2023-04-14 12:29 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11855

2023-04-18 08:50 UTC, MateStrysewske requested changes
Please revert the changes to all captions files; didn't think about them when I created the issue, but they are handled by Crowdin, so doing this manually would only result in additional merge conflicts :)

2023-04-18 15:39 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11855

2023-04-19 10:14 UTC, MateStrysewske approved these changes

2023-04-19 10:15 UTC, merged