#11327 - Show warning hint before restore popup
hzi-braunschweig/SORMAS-Project pull request #11880
Opened 2023-04-20 10:11 UTC by MateStrysewske

Fixes #11327

2023-04-20 10:37 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11880

2023-04-21 12:21 UTC, carina29 requested changes

2023-04-21 12:21 UTC, carina29 commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/DeleteRestoreController.java
> +		if (countNotRestoredEntities == 0) {
I think that would be easier to read this method with some refactorings.
- by extracting countNotRestoredEntities == 0 check into a method with a proper naming for ex: allTheEntitiesAreRestored(countNotRestoredEntities) which would return a boolean

- the code from the else branch could go into a separate method for ex: displayNotRestoredEntities(countNotRestoredEntities, notRestoredEntities)  or some similar naming

2023-04-24 07:43 UTC, merged

2023-04-24 08:05 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11880