#11786 - Delete immunizations in reduced module when the last other e…
hzi-braunschweig/SORMAS-Project pull request #11954
Opened 2023-05-12 06:11 UTC by sergiupacurariu

…ntity related to the person is deleted

Fixes #11786

2023-05-12 06:36 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11954

2023-05-15 08:44 UTC, leventegal-she requested changes

2023-05-15 08:44 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
> +	private Subquery<String> createSubquery(
please rename to `createPersonLinkedToOtherCoreEntitySubQuery`

2023-05-15 08:44 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
> +		Class<? extends CoreAdo> subqueryClass,
please rename to `otherCoreEntityClass`

2023-05-15 08:44 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
> +		Join<Immunization, Person> personJoin,
please rename to `immunizationPerson`

2023-05-15 08:44 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationService.java
> +		String personField) {
please rename to `otherPersonField`

2023-05-16 07:18 UTC, leventegal-she approved these changes

2023-05-16 07:18 UTC, merged