Feature 2526 campaign diagram visualisation
hzi-braunschweig/SORMAS-Project pull request #2665
Opened 2020-08-18 07:57 UTC by BarnaBartha

2020-08-24 11:36 UTC, MateStrysewskeSym requested changes
Looks pretty good to me! The only thing that's not working from my perspective is that the columns don't always have captions (see the attached screenshot).

![diagram_captions](https://user-images.githubusercontent.com/23701005/91040570-c65aee00-e60e-11ea-885b-b019a9184993.png)

2020-08-24 11:36 UTC, MateStrysewskeSym commented on sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/campaigns/CampaignDashboardDiagramComponent.java
> +			// TODO throw exception when entry already exists
Are these TODOs meant to be done in this pull request?

2020-08-25 06:27 UTC, BarnaBartha commented on sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/data/CampaignFormDataFacadeEjb.java
> +//		if (criteria.getCampaignFormMeta() != null) {
yes

2020-08-25 06:29 UTC, BarnaBartha commented on sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/data/CampaignFormDataFacadeEjb.java
> +	public List<CampaignDiagramDataDto> getDiagramData(
i think Martin placed it here since we query the CmapaignFormData table.. but it can go also to the diagram facade

2020-08-25 11:31 UTC, merged