Feat 2622 s2s truststore setup
hzi-braunschweig/SORMAS-Project pull request #2689
Opened 2020-08-24 09:34 UTC by vlad-ciucescu

2020-08-25 11:30 UTC, HolgerReiseVSys commented on sormas-base/setup/import-to-truststore.sh
> +  openssl pkcs12 -export -nokeys -out "${TRUSTSTORE_FILE}" -password pass:"${SORMAS_S2S_TRUSTSTORE_PASS}" -in "${CRT_FILE}" -certfile ${TEMP_FILE}
It seems that the java Keystore ignores plain certificates without alias/friendlyName.
With openssl there seems to be no way to add several certificates with friendlyNames.
So we probably should require Java to be installed and use keytool instead.

2020-08-25 11:35 UTC, HolgerReiseVSys commented on sormas-base/setup/import-to-truststore.sh
> +  DEFAULT_SORMAS2SORMAS_DIR="${ROOT_PREFIX}/opt/sormas2sormas"
If a SORMAS2SORMAS_DIR is specified, but does not exist, the script should fail.

2020-08-25 11:51 UTC, HolgerReiseVSys commented on sormas-base/setup/generate-cert.sh
> +openssl req -sha256 -newkey rsa:4096 -passout pass:"${SORMAS_S2S_CERT_PASS}" -keyout "${PEM_FILE}" -x509 -passin pass:"${SORMAS_S2S_CERT_PASS}" -days 1095 -subj "${CERT_SUBJ}" -out "${CRT_FILE}"
There seems to be a miminum length of 4 characters for the password. Maybe we should check that.

2020-08-26 06:56 UTC, vlad-ciucescu commented on sormas-base/setup/import-to-truststore.sh
> +echo "# This script imports a certificate into the local truststore, to be used for SORMAS2SORMAS and SurvNet communication"
Yeah, removed it for the other ticket to, probably conflict resolution error

2020-08-26 13:35 UTC, JonasCir commented
Thrilled to see S2S work soon :D Maybe add a `docs/` root folder and start to place documentation/guides there? The repo base is already pretty crowded :smiley:

2020-08-28 12:28 UTC, HolgerReiseVSys requested changes
The scripts should have at least soemthing like `s2s` in their names so it is clearer what they are used for.

2020-08-28 12:34 UTC, vlad-ciucescu commented on GUIDE_SORMAS2SORMAS_CERTIFICATE.md
> +    automatically set by the script.
But the script is for generating a new certificate. I don't think it should matter if another one is available and the properties are already set.

2020-08-28 14:22 UTC, vlad-ciucescu commented on GUIDE_SORMAS2SORMAS_CERTIFICATE.md
> +    automatically set by the script.
But I can add this functionality in the case of the truststore password

2020-09-02 08:55 UTC, HolgerReiseVSys approved these changes

2020-09-02 14:15 UTC, merged