Added UUID to Person Edit Form which is read-only
hzi-braunschweig/SORMAS-Project pull request #2693
Opened 2020-08-24 14:50 UTC by fuatse

Add the display of the UUID as requested in issue #2608

2020-08-25 07:17 UTC, MateStrysewskeSym requested changes
First of all, thanks for your submission and for supporting the project!

I'd prefer the UUID field to be read-only instead of not editable to make it appear as a label instead of a disabled text field. Have a look at the CaseDataForm to see how the case UUID is handled there. Also, please make sure to add an entry to the captions.properties file for Person.UUID and use "Person ID" as the value.

2020-08-25 07:17 UTC, MateStrysewskeSym commented on sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
> +	private static final String PERSON_UUID_LOC = "personUUIDLoc";
Should be unneccessary

2020-08-25 13:57 UTC, fuatse commented on sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
> +	private static final String PERSON_UUID_LOC = "personUUIDLoc";
Very true.

2020-09-01 11:43 UTC, MateStrysewske approved these changes
Thank you for implementing the changes. Please make sure to reference the issue number in every commit next time you're contributing!

2020-09-01 11:43 UTC, merged

2020-09-05 17:56 UTC, fuatse commented
> Thank you for implementing the changes. Please make sure to reference the issue number in every commit next time you're contributing!

Noted!