made changes in relation to issue 2332 and closed pull request #2649
hzi-braunschweig/SORMAS-Project pull request #2707
Opened 2020-08-25 21:56 UTC by john1496

Did a refactor of the previous pull request an made all necessary changes

2020-09-29 06:46 UTC, StefanKock requested changes
I commented some points.
In general:
1. please make sure to rebase to current development branch again before push
2. Reference issue/ticket #2332 like I do here and do not reference pull requests in the commit message

2020-09-29 06:46 UTC, StefanKock commented on sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java
> +		List<VisitContactJurisdiction> jurisdictions = em.createQuery(cq).getResultList();
Hint should not be removed here since this queries JPA entities

2020-09-29 06:46 UTC, StefanKock commented on sormas-backend/src/main/java/de/symeda/sormas/backend/util/ModelConstants.java
> +	 * <h2>
h2 is not appropriate, just a <br /> at the end would be enough.

2020-09-29 06:46 UTC, StefanKock commented on sormas-backend/src/main/java/de/symeda/sormas/backend/util/ModelConstants.java
> +	 *<p>
Please use {@code ...} for the example in "..." and check that it gets properly formatted. Then write the Note ... in a new line (I think <br /> will be needed).

2020-10-02 15:13 UTC, closed without merging

2020-10-02 15:14 UTC, john1496 commented
closing this pull request to perform all changes requested afresh