Add externalId to Person and show it on PersonEditForm on German Systems
hzi-braunschweig/SORMAS-Project pull request #2714
Opened 2020-08-26 15:41 UTC by fuatse

Add Person.externalId in domain model and show in PersonEditForm on German Systems #2670

2020-09-03 08:45 UTC, MateStrysewske commented
Hey! Please rebase your branch to the current development branch to get rid of the merge conflicts before we review your pull request. Thanks!

2020-09-07 10:23 UTC, MateStrysewske commented
@fuatse Please also add the field to the mobile app. You don't necessarily have to include it in the forms, but please add it to the entity and database (as explained in the "how to add a new field" guide).

2020-09-17 09:48 UTC, MateStrysewske commented
@fuatse Hey! Sorry that it took me so long to react here. Can you get rid of the conflicts once more? I'll review the PR asap afterwards to make sure that you don't have to do it again.

2020-09-17 21:40 UTC, fuatse commented
> @fuatse Hey! Sorry that it took me so long to react here. Can you get rid of the conflicts once more? I'll review the PR asap afterwards to make sure that you don't have to do it again.

Hello @MateStrysewske No worries, I completely understand how hard it can be managing such situations. Just did the update for issue #2670 . Hope the build is successful

2020-09-18 06:06 UTC, MateStrysewske commented
Two things:

- [ ] Seems like you accidentally removed the external ID from the person form in the web app again
- [ ] In the Android app, you also need to increase the DatabaseHelper.DATABASE_VERSION whenever you add upgrade code. The DATABASE_VERSION always has to be one number higher than the highest CASE statement in the upgrade part.

2020-09-18 12:02 UTC, fuatse commented
> Two things:
> 
> * [ ]  Seems like you accidentally removed the external ID from the person form in the web app again
> * [ ]  In the Android app, you also need to increase the DatabaseHelper.DATABASE_VERSION whenever you add upgrade code. The DATABASE_VERSION always has to be one number higher than the highest CASE statement in the upgrade part.

@MateStrysewske I took out the field after I misunderstood your request for the mobile app. I just added it again. I have equally updated the database version for the mobile app for issue #2670 , Thanks for the heads up

2020-09-22 07:37 UTC, MateStrysewske requested changes
One more rebase and a fix for the little problem I've encountered and I'll merge this!

2020-09-22 07:37 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
> +package de.symeda.sormas.app.backend.person;cd
;)

2020-09-22 21:33 UTC, fuatse commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
> +package de.symeda.sormas.app.backend.person;cd
Grrrrr.... Changes pushed @MateStrysewske

2020-09-23 06:36 UTC, merged