#2542 add filter apply buttons to directories and dashboards
hzi-braunschweig/SORMAS-Project pull request #2796
Opened 2020-09-03 09:56 UTC by vlad-ciucescu

2020-09-03 13:01 UTC, leventegal-she requested changes
Pease remove the non english translations, only captions.properties should be edited.

2020-09-03 14:46 UTC, vlad-ciucescu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskGridFilterForm.java
> +		getContent().removeComponent(APPLY_BUTTON_ID);
But in the case of the task list the only filter we have is the task status. Does it make sense to have an apply button only for only one filter?

2020-09-04 12:26 UTC, leventegal-she approved these changes

2020-09-04 12:26 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskGridFilterForm.java
> +		getContent().removeComponent(APPLY_BUTTON_ID);
Ok, I think it's fine for now, let's see what the users will say

2020-09-04 12:27 UTC, merged