Evol2550rgpd
hzi-braunschweig/SORMAS-Project pull request #3063
Opened 2020-10-05 12:50 UTC by mouloud-mala

2020-10-06 06:07 UTC, MateStrysewske commented
Please refer to the original issue number in your commit messages. It's hard for us to know which issue you're trying to fix with this pull request, especially with such a generic name.

Could you please comment with the issue number that's linked to this pull request?

2020-10-06 06:49 UTC, mouloud-mala commented
Hello, ok for the next work I will make it.

2020-10-07 08:16 UTC, MateStrysewske commented
> Could you please comment with the issue number that's linked to this pull request?

2020-10-07 08:19 UTC, mouloud-mala commented
#2550

2020-10-08 07:24 UTC, MateStrysewske requested changes
* Please have a look at the "Code formatting" section of the Development Environment guide, set up your IDE accordingly and reformat all classes that you've worked on.
* For all fields that you add the GDPR message to, please always APPEND it to the already existing description (it doesn't matter if there is none in the descriptions.properties file, there might be one added in the future) instead of overwriting it

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/user/UserDto.java
> +	private boolean gdpr;
Purpose of this field name is unclear; please choose a more descriptive name

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +messageGdpr = In accordance with the principle of data minimization imposed by the GDPR, you must ensure that you enter here only objective data absolutely necessary for the processing of the file. I
You've accidentally duplicated the text here - also, I'd like to ask you to remove the term "racial" because it's a scientifically refuted concept.

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +messageGdprCheck = I have read the information, the window should not be shown again
Change to "I have read this information, please don't show this window again"

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/User.java
> +	private boolean gdpr;
See UserDto comment

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/pom.xml
> +		<dependency>
Please revert this change, the API is already available to the UI.

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
> +		UserDto user = FacadeProvider.getUserFacade().getCurrentUser();
User should be retrieved with `UserProvider.getCurrent()`

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
> +			Window subWindowGdpR = new Window(I18nProperties.getCaption(Captions.User_gdpr));
Use `I18nProperties.getPrefixCaption` instead and directly reference the static String in UserDto

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
> +			CheckBox checkBoxRgpd = new CheckBox(I18nProperties.getString(Strings.messageGdprCheck));
=> checkBoxGdpr

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
> +						boolean isCheck = checkBoxRgpd.getValue();
Unnecessary line, just write `if (checkBoxGdpr.getValue())`

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
> +		descriptionField.setDescription(I18nProperties.getDescription(Captions.Event_eventDesc) + "\n" + I18nProperties.getDescription(Descriptions.descGdpr));
Use `I18nProperties.getPrefixDescription` for the event description (see above)

2020-10-08 07:24 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/visit/VisitEditForm.java
> +		addField(VisitDto.VISIT_REMARKS, TextField.class).setDescription(I18nProperties.getDescription(Captions.Visit_visitRemarks) + "\n" + I18nProperties.getDescription(Descriptions.descGdpr));;
Use `I18nProperties.getPrefixDescription` for the visit remarks (see above)

2020-10-09 06:56 UTC, mouloud-mala reviewed
All changes have been made

2020-10-09 08:59 UTC, MateStrysewske requested changes
There are still fields where you simply override the description with the GDPR message instead of appending it.

2020-10-09 08:59 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/user/UserDto.java
> +	public static final String GDPR_STANDARDS = "gdprStandards";
Constant needs to have the exact same name as the field

2020-10-09 08:59 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/user/UserDto.java
> +	private boolean gdprStandardsActive;
Suggestion: "hasConsentedToGdpr"

2020-10-09 10:50 UTC, MateStrysewske requested changes

2020-10-09 10:50 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/User.java
> +	public boolean getHasConsentedToGdpr() {
=> isHasConsentedToGdpr is the correct pattern here

2020-10-09 10:50 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/MainScreen.java
> +		if (user.getHasConsentedToGdpr()) {
The logic doesn't match the name of the field. This should be if (!user [...]).

2020-10-09 10:50 UTC, MateStrysewske commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +ALTER TABLE users ADD COLUMN hasConsentedToGdpr boolean default true;
Default should be false combined with the change request in MainScreen.java

2020-10-09 10:50 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java
> +		TextArea descriptionField = addField(EventDto.EVENT_DESC, TextArea.class);
Don't remove existing logic

2020-10-09 10:50 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java
> +		comment.setRows(2);
Please keep the number of rows as they were defined before

2020-10-09 14:42 UTC, MateStrysewske approved these changes

2020-10-09 14:42 UTC, merged