Allow location filters in the event directory to everyone #2914
hzi-braunschweig/SORMAS-Project pull request #3395
Opened 2020-11-05 09:05 UTC by alexandre-gille

Fixes #2914

2020-11-06 08:07 UTC, alexandre-gille commented
:stop_sign: This PR shouldn't be merged yet. A commit is missing. This was developed by another dev and I didn't notice it was in two parts, my bad !

2020-11-20 13:08 UTC, alexandre-gille commented
:green_circle: This PR is now ready.

2020-12-01 09:53 UTC, MateStrysewske requested changes
District filter doesn't work properly for region-level users and community filter doesn't properly work for district-level users. Their content is never updated when the region/district filter is selected. The current logic that the district/community filters are pre-selected based on the user's region/district probably doesn't make sense in this case because all filters are displayed (and none of them is pre-selected).

2020-12-01 09:53 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/location/LocationReferenceDto.java
> +		if (!DataHelper.isNullOrEmpty(houseNumber)) {
I know it's the same as in the other buildCaption method, but there shouldn't be a comma in between street and house number if both are present; would be great if you could also fix that for the above method

2020-12-08 13:57 UTC, MateStrysewske approved these changes

2020-12-08 13:58 UTC, merged