Assigned user missing email at task creation #3273
hzi-braunschweig/SORMAS-Project pull request #3432
Opened 2020-11-09 12:39 UTC by alexandre-gille

Notify at task's creation if the assigned user has no email provided and notifications are enabled

Fixes #3273

2020-11-13 09:59 UTC, MateStrysewske requested changes
* Please also take into account SMS, because users can also be notified via SMS; this of course only makes sense if the SMS_AUTH_KEY and SMS_AUTH_SECRET properties aren't blank (see ConfigFacade); maybe add a `isSmsServiceSetUp` helper method to the config facade; if it returns true, the hint should only be displayed if the user has neither an email address nor a mobile number, and it should then also be extended (=> "... does not have an e-mail address or mobile number provided...")
* The hint should also be displayed when already existing tasks are edited because notifications aren't only sent when a task is supposed to be started, but also when it's due
* Please remember to also add the French translation to Crowdin; else it will be overridden with the default English one because Crowdin seems to have priority when the translations are automatically merged

2020-11-16 10:55 UTC, alexandre-gille commented
>     * Please also take into account SMS, because users can also be notified via SMS; this of course only makes sense if the SMS_AUTH_KEY and SMS_AUTH_SECRET properties aren't blank (see ConfigFacade); maybe add a `isSmsServiceSetUp` helper method to the config facade; if it returns true, the hint should only be displayed if the user has neither an email address nor a mobile number, and it should then also be extended (=> "... does not have an e-mail address or mobile number provided...")
> 
>     * The hint should also be displayed when already existing tasks are edited because notifications aren't only sent when a task is supposed to be started, but also when it's due

Done

>     * Please remember to also add the French translation to Crowdin; else it will be overridden with the default English one because Crowdin seems to have priority when the translations are automatically merged

So, we gotta wait till our PR is merged and then add the french translation on Crowdin (We'll need an access), that's it ?

2020-11-17 08:31 UTC, MateStrysewske commented
@alexandre-gille You can request access in the Crowdin project (don't know where exactly) and then someone from HZI is going to have a look at it and grant you the access. And yes, all you need to do is to translate the strings again there after the PR is merged, correct. I know that it's a bit annoying; once we have the time for it, we'll have a look at the automatic merging process and see whether we can tweak it.

2020-11-17 08:42 UTC, MateStrysewske requested changes
The label that's displayed when both an email address and a phone number are missing is too long for the window and the text is cropped; you should be able to fix this by giving the label a width of 100 %.

2020-11-17 08:42 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java
> +	private void checkIfAssigneeEmailIsProvided(UserReferenceDto assigneeRef) {
Should be called `checkIfAssigneeEmailOrPhoneIsProvided` now

2020-11-17 09:28 UTC, alexandre-gille commented
@MateStrysewske Done !

2020-11-19 08:23 UTC, MateStrysewske requested changes
Hey - looks like you didn't test the change concerning the problems with the label length. You set the width of the surrounding layout, which does nothing; you need to adjust the width of the label instead.

2020-11-19 10:10 UTC, alexandre-gille commented
Sorry about that. Done.

2020-11-19 14:00 UTC, MateStrysewske requested changes
Looks like the layout also needs to be set to full width for this to work. Wasn't aware of that myself, but I just tested it.

2020-11-20 07:37 UTC, merged