#3392 Added duplicate detection for linking cases
hzi-braunschweig/SORMAS-Project pull request #3442
Opened 2020-11-10 09:07 UTC by FredrikSchaeferVitagroup

2020-11-13 10:30 UTC, MateStrysewske requested changes
I'd suggest a different approach:

* Add PersonReferenceDto to EventParticipantCriteria that can be used to check whether the person of the event participant matches the given person
* Add a dedicated "getEventParticipantUuid" method to EventParticipantFacade that receives an EventReferenceDto and a PersonReferenceDto; the method should then manually build an EventParticipantCriteria with these two properties and then query for the uuid of a possible match (should probably still expect a list as the result and then just return the first result if there is any, because it's possible that there are multiple event participants for the same person in the same event in older servers)
* When checking for an existing event participant in the event, use the new method instead of getIndexList

2020-11-13 10:42 UTC, MateStrysewske commented
@FredrikSchaeferVitagroup Pull request #3371 actually adds such a method; you might want to wait with the further development on this PR until that one is merged into development.

2020-12-02 07:21 UTC, FredrikSchaeferVitagroup commented
Once more taken be the infinite wisdom of more experiened developers, I implemented the requested changes.
Please have a look...

2020-12-08 10:41 UTC, MateStrysewske approved these changes

2020-12-08 10:41 UTC, merged