[IMIS] Use Jsoup instead of StringEscapeUtils to sanitize inputs and prevent XSS attacks #3389
hzi-braunschweig/SORMAS-Project pull request #3448
Opened 2020-11-11 11:05 UTC by Seal33

More info can be found in #3389 and #3193 

Jsoup allows the use of custom whitelists to allow certain tags, while still preventing XSS attacks reliably. This is a cleaner and more standardized approach than that of PR #3220 , which will be reverted by this PR. Jsoup was already used in several spots throughout the code.

2020-11-13 12:02 UTC, MateStrysewske commented
@Seal33 Please have a look at #3464; I had to create that issue because apparently `Jsoup.clean` can't deal with null values. I guess that we could and would run into a lot of problems with the current implementation in this PR; my suggestion would be to add some kind of a wrapper method to the API that calls Jsoup.clean if the given string is not null or just returns null again otherwise, and use that everywhere where you've added the call to Jsoup.clean.

2020-11-13 13:05 UTC, Seal33 commented
> @Seal33 Please have a look at #3464; I had to create that issue because apparently `Jsoup.clean` can't deal with null values. I guess that we could and would run into a lot of problems with the current implementation in this PR; my suggestion would be to add some kind of a wrapper method to the API that calls Jsoup.clean if the given string is not null or just returns null again otherwise, and use that everywhere where you've added the call to Jsoup.clean.

Oh, I didn't know that, I'm sorry we didn't catch that during our internal review. I think a wrapper method is a good idea. This would also allow us to create predefined Whitelists in the wrapper.

2020-11-14 16:55 UTC, syntakker commented
@MateStrysewske I think it would make sense to do the sanitizing in the getters and setters of the Dto classes. This way sanitizing would be implemented in one central place and cannot be forgotten in the UI.

2020-11-16 08:19 UTC, MateStrysewske commented
@syntakker That approach could make sense, although it would require developers to remember to add the sanitisation to every getter and setter they're adding. @MartinWahnschaffeSymeda do you have a preference here?

2020-11-19 09:12 UTC, MateStrysewske commented
@syntakker @Seal33 Discussed this with Martin and we came to the conclusion that doing the sanitising in the getters and setters could make sense, but it's too big of a refactoring to be considered right now. We'll got with the solution that you've already implemented for now. I'll review this pull request after the next release.

2020-12-01 09:20 UTC, MateStrysewske requested changes

2020-12-01 09:20 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/utils/HtmlHelper.java
> +		if (string == null)
We're using brackets even for one-line statements; please refactor your code accordingly; also, you could use a shorter syntax for the return statements in this class (e.g. `return string == null ? "" : Jsoup.clean(string, Whitelist.none());`

2020-12-08 10:43 UTC, MateStrysewske commented
@Seal33 Can you solve the merge conflicts again? I'll approve the PR afterwards.

2020-12-08 12:42 UTC, Seal33 commented
@MateStrysewske The merge conflicts are now resolved. However, some tests fail during building. This is most likely caused by development failing tests right now, but I cannot guarantee that the merge itself did not introduce any new problems too. The branch did pass all tests before merging today.

2020-12-10 08:25 UTC, MateStrysewske commented
@Seal33 Should be fine. We'll run manual tests on our system anyway. I don't think that anything that you've done in this PR should result in test failures.

Sorry, you'll have to do some conflict resolving again - I'll try to merge the PR asap afterwards so that you don't have to do it another time.

2020-12-10 10:31 UTC, Seal33 commented
@MateStrysewske Done. I also ran the tests locally with 0 failures.

2020-12-10 10:32 UTC, MateStrysewske approved these changes

2020-12-10 10:32 UTC, merged