[IMIS] Fix #3462 by adding onsetDate caption
hzi-braunschweig/SORMAS-Project pull request #3476
Opened 2020-11-12 19:13 UTC by Seal33

Description of the solution can be found in #3462 , in case identical issues pop up anywhere else

2020-11-13 12:06 UTC, MateStrysewske requested changes
I'm not really happy with this solution. The onset date is not part of the case, and simply adding a caption for the case therefore isn't appropriate. The solution should rather make sure that the validation can handle the caption of fields that are not part of the main DTO of the form. This would also help in other places where this could be a problem as well.

2020-11-13 12:58 UTC, Seal33 commented
> The solution should rather make sure that the validation can handle the caption of fields that are not part of the main DTO of the form. This would also help in other places where this could be a problem as well.

Yes, I've thought about that too. However, I am not exactly sure how to go on about that.
For example if the code can't find `caseData.onsetDate` nor just `onsetDate`, how should it know whicht onsetDate it is supposed to choose instead? In this case it would be easy, as `onsetDate` only appears in one other part (`Symptoms.onsetDate`). However that's not always the case (for example, `Person.firstName` and `Contact.firstName` are very different strings)

The only solutions I see would involve somewhat larger code changes (for example adding additional parameters to "addField").
If you have any other idea please tell me, I will try to come up with something better too. It would indeed be nice to have a more general solution that might work in other places too, however one has to be very careful not to break all the other code parts involving adding Fields and auto-captioning them.

2020-11-14 17:55 UTC, Seal33 commented
I have overloaded the `addCustomField` method with an additional parameter that allows the user to set custom captions. For now, this is by far the easiest and 'safest' solution, which can easily be applied anywhere the same issue arises.

2020-11-16 08:35 UTC, MateStrysewske requested changes
I like that solution! Two more change requests, but the approach is totally fine.

2020-11-16 08:35 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/AbstractEditForm.java
> +	protected <T extends Field> void formatField(T field, String propertyId, String customCaption) {
A lot of duplicated code; this method can stay as it is, but the already existing formatField method should be changed. Basically remove everything but the line that builds the caption and then use that to call the new method:

```
formatField(field, propertyId, I18nProperties.getPrefixCaption(propertyI18nPrefix, propertyId, field.getCaption()));
```

2020-11-16 08:35 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java
> +		addCustomField(SymptomsDto.ONSET_DATE, Date.class, DateField.class, I18nProperties.getCaption(Captions.Symptoms_onsetDate));
Use `I18nProperties.getPrefixCaption` instead

2020-11-20 07:37 UTC, merged