3388 sormas to sormas send back
hzi-braunschweig/SORMAS-Project pull request #3478
Opened 2020-11-13 14:58 UTC by leventegal-she

2020-11-17 07:07 UTC, vidi42 requested changes

2020-11-23 09:19 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/SormasToSormasFacadeEjb.java
> +		caze.getSormasToSormasOriginInfo().setOwnershipHandedOver(false);
`SormasToSormasOriginInfo::ownershipHandedOver` "means" the ownership was handed over to the current system, now when returning the data to the original system this flag should be set to `false` so the the current system will not have access to modify it.

2020-11-23 09:19 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/datapersister/ProcessedDataPersisterHelper.java
> +				if (savedOriginInfo == null) {
it is null only for the first step in the `for` cycle, the origin info gets saved only when needed if there is no new sample returned, then the origin info should not be saved.

2020-11-23 09:19 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/datapersister/ProcessedCaseDataPersister.java
> +					if (savedOriginInfo == null) {
same as for samples

2020-11-23 13:14 UTC, vidi42 approved these changes

2020-11-24 10:02 UTC, merged