Add basic export to the task directory #3275
hzi-braunschweig/SORMAS-Project pull request #3529
Opened 2020-11-18 17:13 UTC by alexandre-gille

Closes #3275

2020-11-18 17:16 UTC, alexandre-gille commented
I'll adjust the allowed roles for the TASK_EXPORT according to answers in #3275.

2020-11-19 08:57 UTC, MateStrysewske requested changes
As long as there's only the basic export, it would be good to have the button directly in the top layout, not hidden behind the popup button (which makes sense otherwise to save space).

2020-11-19 10:00 UTC, alexandre-gille commented
Done

2020-11-19 13:44 UTC, MateStrysewske approved these changes

2020-11-19 13:44 UTC, merged