Add institutional partner option to events source type #3207
hzi-braunschweig/SORMAS-Project pull request #3619
Opened 2020-11-27 16:43 UTC by alexandre-gille

Closes #3207

2020-12-01 10:57 UTC, MateStrysewske requested changes
* EventReadFragment is missing in the app
* There should probably also be a srcInstitutionalPartnerTypeDetails text field in case "Other" is chosen (to allow users to specify it); we have this pattern for all other enums that allow the selection of "Other"

2020-12-01 10:57 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
> +	public static final int DATABASE_VERSION = 248;
There was a mistake by one of our developers in version 247; please increase this to 249 to make it work again

2020-12-02 07:12 UTC, ftavin commented
>     * There should probably also be a srcInstitutionalPartnerTypeDetails text field in case "Other" is chosen (to allow users to specify it); we have this pattern for all other enums that allow the selection of "Other"

Good point ! This is a functional change to be confirmed in the issue with bernard and carolin, I have copy/pasted the question to the issue.

2020-12-02 10:18 UTC, alexandre-gille commented
It's done :heavy_check_mark:

2020-12-08 13:38 UTC, MateStrysewske requested changes

2020-12-08 13:38 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventExportDto.java
> +	public InstitutionalPartnerType getSrcInstitutionalPartnerType() {
Unify this and the details field below and build an appropriate string directly in the constructor (see CaseExportDto.educationType for an example)

2020-12-08 13:38 UTC, MateStrysewske commented on sormas-app/app/src/main/res/layout/fragment_event_read_layout.xml
> +                        app:value="@={data.srcInstitutionalPartnerType}"
Read-only fields can't have an "=" sign after the @ sign (because this is the trigger for two-way databinding)

2020-12-08 15:25 UTC, MateStrysewske requested changes
Have you checked and tested the app? E.g. there's an import for InstitutionalPartnerType missing, so the app is unable to build.

2020-12-08 15:25 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventExportDto.java
> +	private String buildSrcInstitutionalPartnerTypeString(
Move this to a separate EventHelper class (in the api); DTos should ideally not contain such logic. You also don't need a StringBuilder, you can directly return the respective value in the if/else if body.

2020-12-09 09:41 UTC, alexandre-gille commented
> Have you checked and tested the app? E.g. there's an import for InstitutionalPartnerType missing, so the app is unable to build.

Unfortunately, I've never been able to launch the app, following the `DEVELOPMENT_ENVIRONMENT.md`. Hence I cannot test anything at all.
And I don't see where this missing import should be :shrug:

2020-12-09 10:01 UTC, MateStrysewske commented
@alexandre-gille Okay, I'll take care of that this time. But please make sure to get your Android Studio up and running next week. If you need support, drop me a message at our Gitter (it's linked on the main site of this repository). It's really, really important that you test the stuff you're submitting both in the web as well as the mobile app.

2020-12-09 10:58 UTC, MateStrysewske commented
@alexandre-gille Just realised that I of course can't fix this myself because I can't push to your pull request. There's an import for InstitutionalPartnerType missing in Event.java in the mobile app. I'll approve and merge the PR after that's added.

2020-12-09 11:08 UTC, MateStrysewske approved these changes

2020-12-09 11:08 UTC, merged