Add riskLevel to events with cluster status #3271
hzi-braunschweig/SORMAS-Project pull request #3633
Opened 2020-11-30 10:22 UTC by alexandre-gille

Closes #3271

2020-12-08 13:31 UTC, MateStrysewske commented
@alexandre-gille Please resolve the conflicts

2020-12-08 14:27 UTC, alexandre-gille commented
> @alexandre-gille Please resolve the conflicts

Done

2020-12-08 14:49 UTC, MateStrysewske requested changes
* EventReadFragment is missing

2020-12-08 14:49 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/RiskLevel.java
> +public enum RiskLevel {
Rename values to LOW, MODERATE (watch out for the spelling) and HIGH (no need to have the risk behind since the enum is already called RiskLevel)

2020-12-09 10:00 UTC, MateStrysewske requested changes
Looks like you forgot to also adjust the occurrences of the enum values (e.g. in captions.properties); don't forget to also run I18nConstantGenerator again afterwards

2020-12-09 11:03 UTC, MateStrysewske commented
Also, there's still the spelling mistake in there (MODERADE should be MODERATE)

2020-12-09 11:13 UTC, MateStrysewske commented
@alexandre-gille Solve the merge conflicts again please :)

2020-12-09 11:26 UTC, alexandre-gille commented
@MateStrysewske I'm rushing between all these PRs before going on leave, but I'm just doing stupid, silly mistakes... Sorry about that. I guess I really need those days off !

2020-12-09 11:27 UTC, MateStrysewske commented
@alexandre-gille No worries! ;)

2020-12-09 11:29 UTC, MateStrysewske requested changes

2020-12-09 11:29 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/RiskLevel.java
> +	public String toShortString() {
Remove this method (since you've not set up any short versions of the captions in enum.properties and they're also not used anywhere)

2020-12-09 12:12 UTC, MateStrysewske approved these changes

2020-12-09 12:25 UTC, MateStrysewske requested changes
RiskLevel import is missing in EventEditFragment

2020-12-09 14:37 UTC, MateStrysewske approved these changes

2020-12-09 14:37 UTC, merged