3610 bag export rest
hzi-braunschweig/SORMAS-Project pull request #3698
Opened 2020-12-04 12:49 UTC by leventegal-she

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/3610

2020-12-07 09:34 UTC, HolgerReiseVSys commented
@leventegal-she Sorry, I cannot do the review atm

2020-12-09 09:13 UTC, vidi42 commented on sormas-backend/src/main/java/de/symeda/sormas/backend/bagexport/BAGExportFacadeEjb.java
> +	private ConfigFacadeEjbLocal configFacade;
The field doesn't seem to be used

2020-12-09 09:52 UTC, vidi42 requested changes

2020-12-09 09:52 UTC, vidi42 commented on sormas-api/src/main/java/de/symeda/sormas/api/user/UserRole.java
> +	BAG_USER(false, false, false, false, JurisdictionLevel.NONE);
Please add the _BAG_USER constant bellow to be used in the @RolesAllowed annotation
Also add it to the `addAssignableRoles` method

2020-12-09 09:52 UTC, vidi42 commented on sormas-backend/src/main/java/de/symeda/sormas/backend/bagexport/BAGExportFacadeEjb.java
> +	private ConfigFacadeEjbLocal configFacade;
The field doesn't seem to be used

2020-12-10 11:48 UTC, vidi42 approved these changes

2020-12-10 15:03 UTC, merged