Add a means of transports field to events #3618
hzi-braunschweig/SORMAS-Project pull request #3800
Opened 2020-12-15 15:58 UTC by alexandre-gille

Closes #3618

2020-12-18 16:53 UTC, MateStrysewske requested changes
* Move the meansOfTransportDetails field to a separate line; half the screen width is too small for a free text field

2021-01-04 11:48 UTC, MateStrysewske requested changes
Oh, I'm sorry! I was talking about the app, but forgot to specify that. The web app is actually fine the way it was before. Can you revert that change and move the details field in the app to a new line please?

2021-01-04 13:34 UTC, alexandre-gille commented
No worries ;)
It's done

2021-01-04 14:47 UTC, MateStrysewske approved these changes

2021-01-04 14:48 UTC, merged