Add a detailed export to the action view of the event directory #3563
hzi-braunschweig/SORMAS-Project pull request #3803
Opened 2020-12-15 18:35 UTC by alexandre-gille

Closes #3563

2020-12-18 17:12 UTC, MateStrysewske requested changes

2021-01-04 11:15 UTC, alexandre-gille commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventActionExportDto.java
> +	@Order(0)
Oh, I didn't think devs were editing this by hand ! Whenever I have to modify the order I just use a sequence. But if this is really needed, i'll change this.

2021-01-04 11:49 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventActionExportDto.java
> +	@Order(0)
I'm not familiar with that - how exactly are you doing it? Would definitely be better than having to do it by hand!

2021-01-04 13:18 UTC, alexandre-gille commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventActionExportDto.java
> +	@Order(0)
Well I think there's this kind of feature on any major IDE (At least with a plugin). If you are using IntelliJ Idea you can use the String Manipulation plugin and use its 'create sequence' feature (there's also plenty of other useful feature for lazy people like me on this plugin).

2021-01-04 13:26 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventActionExportDto.java
> +	@Order(0)
Fine by me to leave it like this then :)

2021-01-04 13:26 UTC, MateStrysewske approved these changes

2021-01-04 13:27 UTC, merged