#3573 - add description to discard button + navigate back to campaign…
hzi-braunschweig/SORMAS-Project pull request #3929
Opened 2021-01-07 10:36 UTC by BarnaBartha

… data list after save or discard

2021-01-07 14:05 UTC, MartinWahnschaffeSymeda requested changes

2021-01-07 14:05 UTC, MartinWahnschaffeSymeda commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/CampaignController.java
> +		final CommitDiscardWrapperComponent<CampaignFormDataEditForm> component = new CommitDiscardWrapperComponent(form, form.getFieldGroup()) {
@BarnaBartha Please use CommitDiscardWrapperComponent.addCommitListener instead

2021-01-08 15:38 UTC, MartinWahnschaffeSymeda commented
@JonasCir I ran into a strange issue here. The unit test `I18nConstantsUpdatedTest.testConstantsAreUpdated` is failing. The reason is that `I18nConstantGenerator.writeI18nConstantClass` seems to receive the content of a property file from another branch when calling `I18nProperties.class.getClassLoader().getResourceAsStream(propertiesFileName)`. Seems like this is related to the caching mechanism used by the CI server.

I'll work around this by merging the development branch into this branch, but it would be good to at least understand what is going on here. Do you have an idea?

2021-01-08 16:34 UTC, merged

2021-01-11 19:11 UTC, JonasCir commented
@MartinWahnschaffeSymeda Not really :D One thing that I could think of is that some temporary files are written to the directories that are cached and under rare circumstances don't get cleaned up properly and therefore carry over to other branches, but I am guessing. From other projects, I know, that CI caching sometimes just behaves strange, so a simple "have you tried to turn it on and off again" helps :D I keep an eye on it