Update DEVELOPMENT_ENVIRONMENT.md
hzi-braunschweig/SORMAS-Project pull request #3993
Opened 2021-01-14 08:11 UTC by cazacmarin

Those issues needs to be updated/added in the documentation. Who wants, can read them, as they can make easiest setup of dev environments.

2021-01-14 13:44 UTC, StefanKock commented on DEVELOPMENT_ENVIRONMENT.md
> +- Set the project SDK to use the installed Zulu Java 11 SDK
Remove the version totally as with Eclipse. The Java version to use should be singularly mentioned in paragraph "Java" to avoid such mistakes

2021-01-14 13:49 UTC, StefanKock commented on DEVELOPMENT_ENVIRONMENT.md
> +## Enable debugging of the application
Document your remarks under the headlines addressing tools to install: Everything concerning IntelliJ to be mentioned under ##IntelliJ, under a sub headline (###) if needed.

2021-01-14 13:52 UTC, StefanKock commented on DEVELOPMENT_ENVIRONMENT.md
> +## Issues which were found during installation process of the project
This is quite tedious. When we have specific defects in the setup, then we could have a headline at the end of the file and in parallel enhance the automation (tickets to be planned in).
Documentation should not mention persons but state facts.

2021-01-14 13:54 UTC, StefanKock commented on DEVELOPMENT_ENVIRONMENT.md
> +* (3) Passwords are really stored under the file: \opt\domains\sormas\config\domain.xml - but, at the moment when I put the right password, this file has been modified by another process which it put
That's not really true, but might have been a side effect of start/deploy processes while editing. Changing domain.xml while the Payara domain is stopped does avoid such problems and makes sure that settings that can only be changed at domain start will be recognized.

2021-01-14 13:54 UTC, StefanKock commented on DEVELOPMENT_ENVIRONMENT.md
> +* (4) Naming for payara was the wrong one, for the downloaded zip file. Twice was used Zip.zip in the name
Sounds like a defect that can easily be fixed.

2021-01-14 13:57 UTC, StefanKock requested changes
It seems that a lot of valid points are addressed, but should be better structured to fit the IDEs/tools in use.
Defects in documentation or automatisation should be fixed if easily doable or addressed in new tickets to help others for the next time.

2021-01-22 13:38 UTC, MateStrysewske commented
New pull request: #4083

2021-01-22 13:38 UTC, closed without merging