#3753 Add the signal evolution date in the event file and in the event directory
hzi-braunschweig/SORMAS-Project pull request #4001
Opened 2021-01-14 09:29 UTC by aponcon-atolcd

Fixes #3753

2021-01-15 12:45 UTC, aponcon-atolcd commented
Hi
Last modifications are about a rebase on development branch.
While testing the commits, I've encountered an issue in the detailed export of events and event actions (the CSV files are empty and an error alert is showing up).
This issue is also present into the test server so this issue is not related to these commits.

2021-01-15 13:14 UTC, MateStrysewske commented
@aponcon-atolcd Yes, I've already encountered that issue as well. We're working on it!

2021-01-15 13:24 UTC, MateStrysewske requested changes
I think the comment should generally only be displayed in forms when the date has actually been filled in; you've already done that for the read fragment in the mobile app, but I think it should also be the case for edit forms. For the mobile app, you can try using dependencyParentField in combination with dependencyParentVisibility=false and dependencyParentValue=null. Should work, if not you have to fall back to a listener.

2021-01-15 13:24 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
> +				getDao(Event.class).executeRaw("ALTER TABLE events ADD COLUMN signalEvolutionDate timestamp");
Not sure whether it's actually needed, but please add a semicolon to the end of the SQL statement just to be safe

2021-01-18 08:25 UTC, MateStrysewske requested changes
The comment field is still visible in the web UI when no date has been entered

2021-01-18 15:55 UTC, aponcon-atolcd commented
This time the web ui and mobile ui are both modified.
The latest push also contains modification of the labels and property naming.
And the work was also rebased as merge were no longer available.

2021-01-22 13:34 UTC, MateStrysewske commented
@aponcon-atolcd Hey, can you resolve the merge conflicts again please?

2021-01-22 14:08 UTC, aponcon-atolcd commented
@MateStrysewske Done :)

2021-01-22 15:08 UTC, MateStrysewske requested changes
I like the dynamic captions of the two fields! However, "Dropped evolution date" doesn't really make sense; I would prefer to call it "Event evolution date" in this case as well (since "event" is the standard name of the entity).

2021-01-25 10:47 UTC, aponcon-atolcd commented
> I like the dynamic captions of the two fields! However, "Dropped evolution date" doesn't really make sense; I would prefer to call it "Event evolution date" in this case as well (since "event" is the standard name of the entity).

Done :)

2021-01-25 11:23 UTC, MateStrysewske approved these changes

2021-01-25 11:23 UTC, merged