#2447 Prevent unintended page scrolling on create forms
hzi-braunschweig/SORMAS-Project pull request #4158
Opened 2021-01-28 11:55 UTC by DavidBaldsiefen

This should fix #2447 (As well as #3601 and #3850).

However this change might have unintended side effects as it changes some "top-level" css, so the UI should be tested thoroughly.

**Please not that you might need to do a full page-reload as most browsers store css in their caches!**  (Ctrl-F5 on Firefox)

2021-01-29 09:53 UTC, MateStrysewske commented
@DavidBaldsiefen This is definitely not a valid solution because it increases the size of ALL windows to 98 % of the browser height, which looks really, really bad when there's not much content to display.

2021-01-29 10:18 UTC, DavidBaldsiefen commented
> @DavidBaldsiefen This is definitely not a valid solution because it increases the size of ALL windows to 98 % of the browser height, which looks really, really bad when there's not much content to display. We could do this on a form-by-form basis, but that doesn't really help either because it heavily relies on a) the display resolution and b) the zoom factor.

Ok, I see. I tried using max-height too, but for some reason that didn't work. The problem right now is that the forms height is automatically set by vaadin, but removed once a dropdown is opened. Thus, the overflow property breaks. If I understood correctly, this problem only exists with forms extending beyond the screen's size anyway. So a Form-By-Form basis might still be viable, as most common display resulitions and zoom factors should have the same forms extending beyond the screens size (it's mainly contact and event creation tabs).

What struck me as odd is that this issue does not seem to exist with the user creation/edit form.

I'll look for a better solution.

2021-02-02 12:23 UTC, DavidBaldsiefen commented
I've found another possible solution. Locally I couldn't find any negative sideffects on other forms.

The git diff seems to be somewhat confused, but the only changes should be that the white `background-color` for the header is now enforced and that `v-scrollable` now has a fixed max-height, which should prevent it from extending beyond the screens resolution.

2021-02-03 12:26 UTC, MateStrysewske requested changes
The scrolling problem is fixed, but I now don't have any margins in popup windows anymore, which looks really bad (Chrome, Windows 10):

![image](https://user-images.githubusercontent.com/23701005/106746882-72275180-6623-11eb-865e-ce5ec2089ca4.png)

2021-02-03 15:09 UTC, DavidBaldsiefen commented
I knew something was off! But for some reason i couldn't quite put my finger on it. I guess if you stare at css for to long you get some kind off tunnel vision :D
Fix is on the way.

2021-02-04 12:53 UTC, MateStrysewske approved these changes

2021-02-04 12:53 UTC, merged