#4137 enabled and extended covid vaccination info on cases (BE + WEB)
hzi-braunschweig/SORMAS-Project pull request #4228
Opened 2021-02-03 11:41 UTC by leventegal-she

2021-02-03 11:52 UTC, MateStrysewske requested changes

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/resources/validations.properties
> +vaccineDosesFormat="Vaccine dose should be a number between 1 and 10"
Remove the "" signs

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/resources/enum.properties
> +Vaccine.UNKOWN=Unkown
=> UNKNOWN

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/Vaccine.java
> +	Ad26_COV2_S(VaccineManufacturer.JOHNSON_JOHNSON),
put "d" in uppercase as well (not in the translation, just in the enum name)

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/Vaccine.java
> +	PFIZER_BIONTECH(VaccineManufacturer.PFIZER_BIONTECH),
Rename enum value to `COMIRNATY`

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/Vaccine.java
> +	MODERNA(VaccineManufacturer.MODERNA),
Rename enum value to `MRNA_1273`

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/VaccineManufacturer.java
> +	SANOFI_GLAXOSMITHKLINE,
Rename enum value to SANOFI_GSK

2021-02-03 11:52 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/VaccineManufacturer.java
> +	PFIZER_BIONTECH,
Rename enum value to BIONTECH_PFIZER

2021-02-03 16:34 UTC, MateStrysewske requested changes
* Captions for "otherVaccineName" and "otherVaccineManufacturer" are missing
* Add the new fields to the detailed and custom case export (that part was missing in the feature description, sorry!)
* The logic that selects the manufacturer based on the selected vaccine name is executed in the mobile app when opening the edit form, which causes problems when e.g. "Other" vaccine name and "Other" manufacturer are selected; in that case, the manufacturer spinner will be cleared, resulting in data loss; the logic may only be executed when the value is changed by the user

2021-02-03 16:34 UTC, MateStrysewske commented on sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
> +                    <de.symeda.sormas.app.component.controls.ControlSpinnerField
Needs to be a ControlTextEditField

2021-02-03 16:34 UTC, MateStrysewske commented on sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
> +                    <de.symeda.sormas.app.component.controls.ControlSpinnerField
Needs to be a ControlTextEditField

2021-02-04 09:18 UTC, MateStrysewske requested changes
* Make sure that "other manufacturer" and "other vaccine name" are cleared when "Other" is deselected in their respective parent field

2021-02-04 09:27 UTC, leventegal-she commented
> * Make sure that "other manufacturer" and "other vaccine name" are cleared when "Other" is deselected in their respective parent field

```
			FieldHelper.setVisibleWhen(
				getFieldGroup(),
				CaseDataDto.OTHER_VACCINE_NAME,
				CaseDataDto.VACCINE_NAME,
				Collections.singletonList(Vaccine.OTHER),
				true);

			FieldHelper.setVisibleWhen(
				getFieldGroup(),
				CaseDataDto.OTHER_VACCINE_MANUFACTURER,
				CaseDataDto.VACCINE_MANUFACTURER,
				Collections.singletonList(VaccineManufacturer.OTHER),
				true);

```

This is the setup for hiding the `other...` fields, the last parameter set to `true`, this mieans they will be cleared when they get hidden.

2021-02-04 09:34 UTC, merged