#3957 Add typing ID to specific pathogen test types
hzi-braunschweig/SORMAS-Project pull request #4232
Opened 2021-02-03 14:47 UTC by DavidBaldsiefen

Closes #3957

2021-02-03 15:21 UTC, MateStrysewske requested changes

2021-02-03 15:21 UTC, MateStrysewske commented on sormas-app/app/src/main/res/layout/fragment_pathogen_test_read_layout.xml
> +                    <de.symeda.sormas.app.component.controls.ControlTextReadField
Typing ID here should also only be visible for the three pathogen test types; also, you don't need a wrapping LinearLayout when you use the ControlSingleColumnStyle

2021-02-04 09:28 UTC, tkaefer reviewed
LGTM, besides the remarks from @MateStrysewske

2021-02-04 13:28 UTC, MateStrysewske commented
@DavidBaldsiefen Can you solve the merge conflicts again please? :)

2021-02-04 13:39 UTC, DavidBaldsiefen commented
@MateStrysewske done

2021-02-04 14:17 UTC, MateStrysewske approved these changes

2021-02-04 14:17 UTC, merged