bugfix #4110
hzi-braunschweig/SORMAS-Project pull request #4263
Opened 2021-02-05 07:37 UTC by Toap777

Table-header is now shown properly while sorting a column.
![Fix](https://user-images.githubusercontent.com/44776957/107003629-6192ea80-678d-11eb-9f08-7c2c105cc8f3.png)

-added non breaking whitespace to all places where tables are used tables
-added styles to table-header-cellasc and table-header-cell-desc. This classes should now work exactly like table-header-cell

2021-02-05 09:30 UTC, JonasCir commented
@MateStrysewske 

@Toap777 is new in our team and wants to contribute to this open source project! :)

2021-02-05 12:46 UTC, MateStrysewske commented
@Toap777 Hey! Thanks for contributing! Please read through the guidelines though, specifically the section about setting up your IDE with automatic code formatting, and apply that to all classes that you are working on (and have worked on in this PR).

2021-02-15 09:54 UTC, MateStrysewske requested changes
Code formatting

2021-02-17 15:13 UTC, MateStrysewske approved these changes

2021-02-17 15:13 UTC, merged