#4185 Add event generation to devmode
hzi-braunschweig/SORMAS-Project pull request #4287
Opened 2021-02-08 09:50 UTC by DavidBaldsiefen

Closes #4185 and also #3338 (some other issues regarding the existing case and contact generation were solved too).

Moving the generation to the backend needs to be handled in another issue, as it's not that important at the moment.

2021-02-08 12:39 UTC, MateStrysewske requested changes
* The script currently can create cases resulting from events with a disease that differs from the event disease; cases resulting from events can not have a different disease than the event disease; events WITHOUT a disease shouldn't have any resulting cases at all

2021-02-08 12:39 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java
> +		"Carinval" };
=> Carnival

2021-02-08 12:39 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java
> +		if (max <= min)
Use brackets even for one-line statements, please

2021-02-08 12:39 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java
> +		Disease disease = config.getDisease();
Move this definition one line up, you can then use it as well in the definition of `List<Disease> diseases`

2021-02-08 12:39 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/configuration/DevModeView.java
> +			if (this.percentageOfCases >= 100)
Use brackets

2021-02-08 12:56 UTC, DavidBaldsiefen commented
> The script currently can create cases resulting from events with a disease that differs from the event disease; cases resulting from events can not have a different disease than the event disease; events WITHOUT a disease shouldn't have any resulting cases at all

Thanks for the review! Currently, my intention was that events where no disease is selected will be created with a random disease, and thus all participants and resulting cases will also have that diesease. Would that be ok? (It will still require me to change a line I missed).

Alternatively one could create disease-less events with no cases or contacts

2021-02-09 14:39 UTC, MateStrysewske requested changes
I still get cases with diseases that differ from the event diseases. For example, I just generated 10 events with Measles, and the while some of the cases resulting from these events are Measles case, I also have some with Meningitis, Polio, Dengue, Cholera, etc. It seems like the event disease is overridden when the case is actually created.

2021-02-09 15:57 UTC, DavidBaldsiefen commented
@MateStrysewske it should work now, thanks for the review!

2021-02-11 12:55 UTC, MateStrysewske approved these changes

2021-02-11 12:55 UTC, merged