3419 suspicious case to cases
hzi-braunschweig/SORMAS-Project pull request #4318
Opened 2021-02-09 13:44 UTC by cazacmarin

2021-02-09 14:41 UTC, leventegal-she requested changes
Didn't see the logic for "If the answer is “suspicion not confirmed” then change case classification to “no case”."

2021-02-09 14:41 UTC, leventegal-she commented on sormas-api/src/main/resources/captions.properties
> +VaccinationInfo.vaccination=Vaccination status for this disease
these are not needed here

2021-02-09 14:41 UTC, leventegal-she commented on sormas-api/src/main/resources/enum.properties
> +# VaccineManufacturer
please delete these ones and from all other enum.properties files

2021-02-09 14:41 UTC, leventegal-she commented on sormas-api/src/main/resources/validations_de-CH.properties
> +vaccineDosesFormat=Impfstoffdosis sollte eine Zahl zwischen 1 und 10 sein
please delete this and from all other validations.properties files

2021-02-09 14:41 UTC, leventegal-she commented on sormas-app/app/src/main/res/layout/dialog_exposure_read_layout.xml
> +                <de.symeda.sormas.app.component.controls.ControlTextReadField
this has nothing to do with your task, please do a proper merge with the development branch

2021-02-09 14:41 UTC, leventegal-she commented on sormas-app/app/src/main/res/layout/dialog_exposure_read_layout.xml
> +                <de.symeda.sormas.app.component.controls.ControlTextReadField
same as above

2021-02-09 14:41 UTC, leventegal-she commented on sormas-app/app/src/main/res/layout/fragment_case_edit_layout.xml
> +                <LinearLayout
This has nothing to do with your ticket, please do a proper merge with the development branch

2021-02-09 14:41 UTC, leventegal-she commented on sormas-base/setup/sormas.properties
> +
please delete this, or do a proper merge with the development branch

2021-02-12 10:24 UTC, MateStrysewske commented
@cazacmarin @leventegal-she I guess this pull request can be closed because you opened a new one to address the issues, right?

2021-02-12 12:27 UTC, closed without merging