#3481: Added missing indexes for queries on tables related to saving …
hzi-braunschweig/SORMAS-Project pull request #4333
Opened 2021-02-10 13:49 UTC by ssferrazza

Added missing indexes for queries on tables related to saving and reading a case.

2021-02-11 09:39 UTC, DavidBaldsiefen commented
Can you also add an index to `users.uuid` and `user.userName`? Also, the two indexes I asked you to add, maybe it's better if we don't define `USING HASH` for them.

2021-02-11 10:00 UTC, ssferrazza commented
@DavidBaldsiefen I'll add the two indexes to `users.uuid` and `user.userName`.

2021-02-15 10:15 UTC, DavidBaldsiefen requested changes

2021-02-15 10:15 UTC, DavidBaldsiefen commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +CREATE INDEX IF NOT EXISTS idx_contacts_reporting_user_id ON contact USING btree (reportinguser_id);
Change name to `idx_contact_reporting_user_id`

2021-02-15 10:15 UTC, DavidBaldsiefen commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +CREATE INDEX IF NOT EXISTS idx_diseaseconfig_changedate on diseaseconfiguration (changedate DESC);
Change name to `idx_diseaseconfiguration_changedate`

2021-02-15 10:16 UTC, DavidBaldsiefen commented
After that you will need to merge sormas_schema.sql, so you will propably need to increase the schema_version number

2021-02-15 11:39 UTC, DavidBaldsiefen requested changes

2021-02-15 11:39 UTC, DavidBaldsiefen commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +
Insert comment including date (see code above for examples)

2021-02-15 12:51 UTC, DavidBaldsiefen approved these changes

2021-02-15 12:51 UTC, merged