#4307 - add indexes
hzi-braunschweig/SORMAS-Project pull request #4340
Opened 2021-02-11 07:58 UTC by BarnaBartha

2021-02-11 08:56 UTC, DavidBaldsiefen requested changes
Looks good to me. We will have to see how this performs on life systems. Also, these changes might lead to quite long transition times when servers with large databases are updated, as all these indexes need to be created first.

The new indexes in the contact and case directory could actually _slow down_ the case/contact import. So I am not sure if it is wise to implement them now. Maybe @MartinWahnschaffe can take a quick look?

2021-02-11 08:56 UTC, DavidBaldsiefen commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +CREATE INDEX IF NOT EXISTS idx_contact_person_id ON contact (person_id);
Remove this line, index already exists

2021-02-11 08:56 UTC, DavidBaldsiefen commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +CREATE INDEX IF NOT EXISTS idx_visit_case_id ON visit (caze_id);
Remove, already exists

2021-02-16 12:19 UTC, MartinWahnschaffe commented
@DavidBaldsiefen The indices Barna added are all for relations that are at the heart of the system and are relevant for almost all queries done. I'm pretty sure this will outweigh the cost of maintaining the index.

@BarnaBartha I think we should also consider the references within the event participant. Also what do you think about adding indices to the reporting user of at least case and contact? The createUserFilter logic is executed for almost all queries and relies on this.

2021-02-16 13:51 UTC, BarnaBartha commented
@MartinWahnschaffe added the indexes to eventParticipants>
The reporting user indices have already been added by Salva
https://github.com/hzi-braunschweig/SORMAS-Project/pull/4333/files

2021-02-16 14:13 UTC, MartinWahnschaffe commented
@BarnaBartha Great. Please go ahead and merge once the checks have passed. Please provide the SQL for all indices with a short message to @StefanKock for the release notes page.

2021-02-16 14:27 UTC, merged