#4290 add community officer role
hzi-braunschweig/SORMAS-Project pull request #4369
Opened 2021-02-12 14:12 UTC by DavidBaldsiefen

Closes #4290.

The given rights are loosely based on COMMUNITY_INFORMANT and CASE_OFFICER roles. The idea was to rather give this user more rights than necessary, instead of ending up with additional requests for another userrole with more rights. All this should no longer be necessary when the new user role system arrives.

2021-02-17 14:43 UTC, MateStrysewske requested changes

2021-02-17 14:43 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java
> +			COMMUNITY_OFFICER
Remove this user right, should only be available to supervisor roles and above

2021-02-17 14:43 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/user/UserRight.java
> +			COMMUNITY_OFFICER
Accidentally added twice here

2021-02-17 15:36 UTC, MateStrysewske commented
@DavidBaldsiefen Can you please resolve the merge conflicts before I test it in the UI?

2021-02-17 15:52 UTC, DavidBaldsiefen commented
@MateStrysewske done

2021-02-17 16:15 UTC, MateStrysewske requested changes
Seems to work fine, the only thing I'd change is to give Community Officers access to the surveillance and contact dashboards (since they also have the respective view and edit rights)

2021-02-17 16:19 UTC, DavidBaldsiefen commented
> Seems to work fine, the only thing I'd change is to give Community Officers access to the surveillance and contact dashboards (since they also have the respective view and edit rights)

I agree, but I will need to check if the dashboards are filtered correctly. I am not sure if that is the case at the moment, I will check it out tomorrow

2021-02-18 08:50 UTC, DavidBaldsiefen commented
I checked it locally in the UI, looks good to me!

2021-02-18 10:37 UTC, MateStrysewske approved these changes

2021-02-18 10:37 UTC, merged