#4044 Limit the information exported to the lines selected in the list of the directory
hzi-braunschweig/SORMAS-Project pull request #4424
Opened 2021-02-17 09:48 UTC by mpe-a

Closes #4044

2021-02-22 07:59 UTC, ftavin commented
@MateStrysewske I'm not sure you had the information but "mpe-a" (Mathieu) is a developper from my team, he is joining the SORMAS effort while Alexandre is shifting on another project for a while

2021-02-24 16:43 UTC, MateStrysewske requested changes
I'd like you to get rid of the new captions that you added to the properties again; they should be handled either by the Location captions (e.g. house number, postal code, etc.) or by the general captions without a prefix (first name, last name, region, district, ...) - I think it should already work like this for the other exports

2021-02-24 16:43 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java
> +					menuBarItems.add(
I think this should be removed

2021-02-24 16:43 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportWithSelectedItemStreamResource.java
> +public class GridExportWithSelectedItemStreamResource extends StreamResource {
Rename to `GridExportWithSelectedItemsStreamResource`

2021-02-24 16:48 UTC, MateStrysewske commented
@ftavin @mpe-a I'm off work for the next days and will be back on Tuesday. I'll continue reviewing pull requests then!

2021-03-02 14:34 UTC, MateStrysewske requested changes
* Remove the newly added captions; they should be handled by the captions that are already there (either with the Location prefix, e.g. street, or without a prefix, e.g. first name); you probably need to add fallbacks to the code that creates the captions for the event participants export file; there probably has to already be such a mechanism in place for e.g. the case export because that also contains first and last name

2021-03-03 15:02 UTC, MateStrysewske requested changes
* Event actions export (Events -> Toggle to "Actions" on top -> Export) is not working anymore
* Basic event participant export is broken (has no file extension) - not sure whether this is because of changes in this PR, but it would be great if you could fix it

The new logic is not implemented/working for
* Basic task export
* Case follow-up visits
I think it would be good to have it for these exports as well to be consistent throughout the whole application

2021-03-04 10:42 UTC, mathieu-petit-atol commented
> The new logic is not implemented/working for
> 
> * Basic task export
> * Case follow-up visits
>   I think it would be good to have it for these exports as well to be consistent throughout the whole application

I did it for the task directory but for the case follow-up visits it would seem that they are no bulk edit option on this page (and they are no export button too).

2021-03-04 11:43 UTC, MateStrysewske commented
> I did it for the task directory but for the case follow-up visits it would seem that there are no bulk edit option on this page (and there are no export button too).
Have you tried to log in as a user with the user roles admin + national user? I recommend that for most development work because it allows you to see all the functionality in the system.

Another option is that I didn't make clear what I meant - I'm not talking about the general follow-up overview of all cases, but about the follow-up tab inside a single case. The grid in there is by default in bulk edit mode and has an export functionality, similar to the follow-up tab inside a single contact.

2021-03-04 15:09 UTC, MateStrysewske commented
Sorry for the amount of merge conflicts today, there's a lot of activity because we approach the end of the sprint. Can you resolve them please?

2021-03-05 13:26 UTC, MateStrysewske approved these changes

2021-03-05 13:26 UTC, merged