#4332: Copy followup comment when converting contact to case
hzi-braunschweig/SORMAS-Project pull request #4535
Opened 2021-02-24 16:43 UTC by ChristopherRiedel

#4332

2021-03-02 07:41 UTC, BarnaBartha approved these changes

2021-03-02 15:26 UTC, MateStrysewske requested changes

2021-03-02 15:26 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
> +					new StringBuilder(entity.getFollowUpComment()).append(" ")
Tests are failing. I suspect this is the reason and that StringBuilder doesn't like to be initiated with null.

2021-03-04 12:54 UTC, MateStrysewske approved these changes

2021-03-04 12:54 UTC, merged