Add Github Actions Super-linter to SORMAS
hzi-braunschweig/SORMAS-Project pull request #4563
Opened 2021-02-27 15:12 UTC by jlewis91

# Add Github Actions Super-linter to SORMAS

## Feature Description

Adds automated lint checks to the SORMAS project which covers 'almost all' languages included in the SORMAS project.
This is intended as 'guardrails' and additional project automation to automatically enforce basic questions of formatting.
This Github action **does not** get everything right and is somewhat opinionated; that said, each language can be toggled
on and off individually so that, for example, the SORMAS project can enforce its own conventions when it comes to Java or
other intensively used languages. For everything else (.env, markdown, etc.), the super-linter offers 'smart defaults'.

## Problem Description

The SORMAS project, like most large software projects uses a primary langugage, in this case Java, and numerous secondary languages
(SQL, R, bash, markdown, Javascript, etc.); ensuring code quality and code consistency is a lot of work when done manually. This
is where automated linters come in. Freqently, however, introducing new linters to a project is an opt-in process in which
linters are individually asssessed for secondary programming languages and document formats. This eats up a lot of time
and does not contribute to significant value generation. With opt-in linting, most projects end up 'under-linted'.

## Proposed Change

Add Super-linter to the Sormas project as a basic quality gate for pull requests, to enforce consistent standards across
many file types and increase PR review automation as a way of enabling broader open source participation in the project.

## Possible Alternatives

Manually add linters for each and every of the languages used in the SORMAS project. Or decide that formatting consistency
is not necessary for the project.

## Additional Information

This PR is split into two commits, one for adding the github action so that files are linted 'on-change' and another
which highlights a number of minor inconsistencies which could be eliminated through the introduction of this github action.

The [github/super-linter](https://github.com/github/super-linter) is developed as open source software by Github itself.

The following languages are currently deactivated (because linting currently fails), but could be reactivated one
by one in a later stage:

```yaml
VALIDATE_BASH: false
VALIDATE_CSS: false
VALIDATE_HTML: false
VALIDATE_JAVA: false
VALIDATE_JAVASCRIPT_STANDARD: false
VALIDATE_JSCPD: false
VALIDATE_R: false
VALIDATE_RUST_2015: false
VALIDATE_RUST_2018: false
VALIDATE_SQL: false
VALIDATE_TYPESCRIPT_ES: false
VALIDATE_TYPESCRIPT_STANDARD: false
VALIDATE_XML: false
```

2021-03-01 10:34 UTC, JonasCir commented
Hi @jlewis91 thank you for contributing! The team will take a closer look shortly :)
In the meantime, I kindly ask you to take care of some formalities laid out in [Contribution guidelines](https://github.com/hzi-braunschweig/SORMAS-Project/blob/8c7af3ec6fb1252127ad380f2e96cf0ad8f18691/CONTRIBUTING.md):

1. Open an associated issue: Copying the text from the PR description should be fine
2. amend your commit messages, they should contain the issue number of the issue you just created e.g., `[#1234] some message`

Thank you :rocket:

2021-03-01 10:40 UTC, JonasCir commented on .github/workflows/linter.yml
> +          DEFAULT_BRANCH: master
Try to use `$default-branch` here and if this does not work `development`

2021-03-01 10:44 UTC, JonasCir commented
Interesting, I was not ware of this github linter! The action itself looks good to me (module the one comment regarding default branch as we use `development`).

2021-03-01 10:49 UTC, JonasCir commented on .github/workflows/linter.yml
> +    branches: [master]
`branches: [ development ]`

2021-03-01 10:49 UTC, jlewis91 commented
@JonasCir Thanks for the prompt and friendly review! Made the fixes you suggested, let me know if anything else comes up (the fun part comes next...turning on the rest of the linters one by one ;) )

2021-03-01 10:57 UTC, JonasCir commented
@jlewis91 thank you!
With the recent change of the default branch, we can see how it will [look](https://github.com/hzi-braunschweig/SORMAS-Project/pull/4563/checks?check_run_id=2003141510) 
> the fun part comes next...turning on the rest of the linters one by one ;)

I hear you :smile:

2021-03-01 11:01 UTC, jlewis91 commented
@JonasCir AFAIK, you have to look in the logs for the offending line, best case is to search for `[ERROR]` in the build

2021-03-01 11:05 UTC, JonasCir commented
Ok fine with me :+1: (inline warnings might be the case if the files _included_ in the PR are badly styled (I saw that in the past somewhere))

2021-03-03 10:09 UTC, JonasCir requested changes
This is great, minor remarks and a merge conflict, otherwise lgtm.

2021-03-03 17:51 UTC, jlewis91 commented on CODE_OF_CONDUCT.md
> +[homepage]: https://www.contributor-covenant.org
Good question, it's a markdown link reference, used in line 70

Syntax: https://gist.github.com/emedinaa/28ed71b450243aba48accd634679f805

2021-03-03 17:54 UTC, jlewis91 commented on SERVER_SETUP.md
> +<!-- markdownlint-disable-next-line MD013 -->
Nice catch, fixed.

2021-03-03 19:06 UTC, jlewis91 commented on GUIDE_SORMAS2SORMAS_CERTIFICATE.md
>          ```shell script
Not sure what you mean here, can you clarify?

2021-03-03 19:24 UTC, jlewis91 commented
@JonasCir think this PR is ready now, just one last comment of yours which I wasn't sure how to resolve, let me know. :)

2021-03-04 08:09 UTC, JonasCir commented on GUIDE_SORMAS2SORMAS_CERTIFICATE.md
>          ```shell script
I think it should be `bash` instead of  shell script. bash is used as specifier in the other places I saw.

2021-03-04 08:48 UTC, jlewis91 commented on GUIDE_SORMAS2SORMAS_CERTIFICATE.md
>          ```shell script
```suggestion
        ```bash
```

2021-03-04 08:49 UTC, jlewis91 commented on GUIDE_SORMAS2SORMAS_CERTIFICATE.md
>          ```shell script
Now I see it, thanks. Fixed.

2021-03-04 08:52 UTC, jlewis91 commented
@JonasCir  Good to go. :)

2021-03-04 14:59 UTC, JonasCir approved these changes
Thank you for your contribution! :rocket: 
lgtm

2021-03-04 15:00 UTC, merged