Feature/4271 add population data to communities
hzi-braunschweig/SORMAS-Project pull request #4687
Opened 2021-03-08 19:28 UTC by arrol

Added Possibilty to import/export populationData on community base.
Incidence can now be calculated for communitys, in Statistic View.

2021-04-06 10:29 UTC, MateStrysewske requested changes
Hey! Sorry that the review took so long. I don't see any problems with the code so far. Can you please correct the two naming issues and resolve the merge conflict? I'll then test the feature and merge it if everything works fine.

2021-04-06 10:29 UTC, MateStrysewske commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +INSERT INTO schema_version (version_number, comment) VALUES (354, 'Add Community Referenz to PopulationData entity #4271');
Referenz => reference

2021-04-06 10:29 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/importer/PopulationDataImporter.java
> +					List<CommunityReferenceDto> communitys = FacadeProvider.getCommunityFacade().getByName(values[i], district, false);
communitys => communities

2021-04-06 10:49 UTC, arrol commented
No problem for me, David told me already, that the timing for the last sprint, would be pretty close :)
Typo's and merge conflict should be fixed now.

2021-04-07 10:16 UTC, MateStrysewske approved these changes

2021-04-07 10:16 UTC, MateStrysewske commented
Thanks! Works fine!

2021-04-07 10:16 UTC, merged