Feature 2744 person contact details
hzi-braunschweig/SORMAS-Project pull request #4731
Opened 2021-03-11 13:05 UTC by BarnaBartha

2021-03-11 15:03 UTC, MateStrysewske requested changes

2021-03-11 15:05 UTC, MateStrysewske commented
In addition to these change requests, please also check that this has been done, because I think it hasn't - or I've missed it:

Keep the field names "phone" and "emailAddress" in CaseExportDto and ContactExportDto and rename the i18n person properties to "Primary phone number" and "Primary email address"; we don't have to write a migration script for export configurations this way; phone should therefore contain the primary phone number (only the number) and emailAddress the primary email address. Add another column otherContactDetails (includes the contactInformation value plus the type value in brackets; details instead if type is "Other");

2021-03-11 19:34 UTC, BarnaBartha commented on sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonContactDetail.java
> +public class PersonContactDetail extends AbstractDomainObject {
at some point we had a ticket to have a common solution for text field lengths with COLUMN_LENGTH_DEFAULT and COLUMN_LENGTH_BIG - why shouldn't we use that?

2021-03-11 19:37 UTC, BarnaBartha commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +
i don't understand this

2021-03-12 06:30 UTC, BarnaBartha commented on sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
> +		final PersonContactDetailDto pcd =
indeed it is safer that way

2021-03-12 06:37 UTC, BarnaBartha commented on sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
>  public class PersonDto extends PseudonymizableDto {
i'm not against this but i think that is a bad decision at the converter side, and a third party influences our code

2021-03-12 07:38 UTC, BarnaBartha commented on sormas-app/app/src/main/java/de/symeda/sormas/app/person/edit/PersonEditFragment.java
> +			dialog.setPositiveCallback(() -> {
forgot that i can use lambda callback, ok

2021-03-12 07:44 UTC, BarnaBartha commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +ALTER TABLE personContactDetail ALTER COLUMN sys_period SET NOT NULL;
isn't this used for the versioning mechanism we have for history tables ? afik this is how it is done for all history tables

2021-03-12 07:51 UTC, BarnaBartha commented on sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonContactDetailsField.java
> +			return personContactDetailDto.isThirdParty() ? personContactDetailDto.getThirdPartyRole() : THIS_PERSON;
The third party role and name currently are free texts, i am not sure how do we want to internationalise them?

2021-03-17 14:24 UTC, MateStrysewske requested changes
* Fix entries not appearing in the list after saving in the mobile app
* Fix entries not updating after removing the primary label from them both in web and mobile app

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
> +//		for (String otherContactDetail : otherContactDetails) {
Remove this code

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
> +	@Order(171)
Move this to next to the primary email address and phone number

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactExportDto.java
> +	@Order(118)
See above

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/person/PersonContactDetailDto.java
> +	public static final String PRIMARY = "primaryContact";
Not fixed yet

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
> +		final PersonContactDetailDto pcd =
Renaming needs to be done

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/person/PersonContactDetailDialog.java
> +	public void configureAsPersonContactDetailDialog(boolean showDeleteButton) {
Check again

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-app/app/src/main/res/layout/dialog_person_contact_detail_edit_layout.xml
> +            <de.symeda.sormas.app.component.controls.ControlCheckBoxField
Check whether this has been done (and whether it's maybe better to use app:caption here)

2021-03-17 14:24 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
> +		// fixme - why was this added?
To make sure that visits are loaded because I think they're lazy; remove this comment

2021-03-18 11:03 UTC, MateStrysewske commented
Other To-Dos:
* Replace "true" and "false" in the table (web) with Yes/No or checkmarks

2021-03-18 14:55 UTC, merged