Add a button to unlink cases from events #2984
hzi-braunschweig/SORMAS-Project pull request #4753
Opened 2021-03-12 14:54 UTC by mathieu-petit-atol

Closes #2984

2021-03-15 15:41 UTC, MateStrysewske requested changes
I feel like the PR is incomplete; at least I can't find any code that adds the icon that can be clicked to unlink cases from events. Is there something I'm missing?

2021-03-15 15:41 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +messageEventParticipationUnlinked = The link between this cases and the event was successfully removed
this cases => this case

2021-03-15 15:41 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +unlinkPopupCaption = Are you sure you want to unlink this case from this event ?
Change the property name to `confirmationUnlinkCaseFromEvent`

2021-03-16 08:51 UTC, mathieu-petit-atol commented
> I feel like the PR is incomplete; at least I can't find any code that adds the icon that can be clicked to unlink cases from events. Is there something I'm missing?

It's done with the `addUnlinkEventListener` variable ; when you set this variable it's automatically show the unlink button with the function `drawDisplayedEntries` in the `EventList` class.

2021-03-16 09:35 UTC, MateStrysewske commented
> > I feel like the PR is incomplete; at least I can't find any code that adds the icon that can be clicked to unlink cases from events. Is there something I'm missing?
> 
> It's done with the `addUnlinkEventListener` variable ; when you set this variable it's automatically show the unlink button with the function `drawDisplayedEntries` in the `EventList` class.

Ah, sorry! Stupid me! :D Thanks for the clarification.

2021-03-16 15:46 UTC, MateStrysewske requested changes
The popup currently has the same heading and caption; heading should be shorter, e.g. "Unlink case from event"

2021-03-16 15:46 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +confirmationUnlinkCaseFromEvent = Are you sure you want to unlink this case from this event ?
Move the property to the section in this file that contains the other confirmations and remove the whitespace before the question mark

2021-03-17 11:41 UTC, MateStrysewske requested changes

2021-03-17 11:41 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +confirmationUnlinkCaseFromEventHeader = Unlink case from event
Call this headingUnlinkCaseFromEvent and move it to the heading section, please

2021-03-18 15:08 UTC, MateStrysewske commented
@mathieu-petit-atol Thanks! Sorry for the inconvenience, but there's another merge conflict (that probably came in today) - can you fix that again? Apart from that, the PR is ready to be merged.

2021-03-18 15:36 UTC, mathieu-petit-atol commented
Done

2021-03-18 15:37 UTC, MateStrysewske approved these changes

2021-03-18 16:23 UTC, merged