#4690 - Prompt default users to change their password on login
hzi-braunschweig/SORMAS-Project pull request #4875
Opened 2021-03-24 15:09 UTC by schwzr

# What does this PR do?

- This PR fixes #4690.
- It provides a new feature to present a prompt at login to any of the standard users with their standard password (as defined in `StartupShutdownService:createDefaultUsers`) to change their password. 
- If we have an elevated user capable of editing other users, this user can change the standard password of other standard users as well. The new passwords can be exported as CSV.
- The attached screencast demonstrates this new feature:

![sormas-4690](https://user-images.githubusercontent.com/5512013/112333683-19874300-8cbb-11eb-9aa1-64f374ac4435.gif)

We are happy to receive feedback from your side!

2021-04-01 10:34 UTC, MateStrysewske requested changes
Hey! Thanks for your contribution! Seems like your IDE settings aren't quite correct when it comes to import orders. java imports are supposed to be above the symeda imports. Please make sure that your IDE is set up correctly and re-format your files.

2021-04-01 10:34 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/utils/DefaultUserHelper.java
> +	public static boolean otherUsersWithDefaultPassword(List<UserDto> allUsersWithDefaultPassword, UserDto currentUser) {
Rename to `otherUsersUseDefaultPassword`

2021-04-01 10:34 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/login/DefaultPasswordOtherScreen.java
> +public class DefaultPasswordOtherScreen extends Window {
Rename to `ChangeDefaultPasswordsWindow`

2021-04-01 10:34 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/login/DefaultPasswordOwnScreen.java
> +public class DefaultPasswordOwnScreen extends Window {
Rename to `ChangeDefaultUserPasswordWindow`

2021-04-01 11:41 UTC, schwzr commented
Thanks @MateStrysewske. I updated my IDE settings to not revert the import ordering of the Eclipse Code Formatting Plugin automatically and renamed the classes and method names as you requested.

2021-04-06 09:54 UTC, MateStrysewske approved these changes
Thank you! Android indeed supports some Java 8 features, but it's still using Java 7 at its core, and it especially requires external code resources (just like our API) to be written in Java 7, unfortunately.

Also, for future reference if you want to contribute code to this repository again - please make sure that every commit always references the issue number (not just the first one). That's important for us to ensure a clean commit history. I've overseen it myself when I did my initial review, so it's alright for now. :)

2021-04-06 09:54 UTC, merged

2021-04-06 10:49 UTC, rzo1 commented
@MateStrysewske Thanks for your time reviewing our pull request. For future contribution, we will adhere to the contribution guidelines. May I ask, if this will be included in the upcoming release?

2021-04-06 11:11 UTC, MateStrysewske commented
@rzo1 Yes, this feature will be part of 1.59.0!