Add a FeatureType for enabling or disabling sending a notification when a case is confirmed
hzi-braunschweig/SORMAS-Project pull request #4894
Opened 2021-03-26 10:09 UTC by aponcon-atolcd

Closes #4732

2021-03-26 10:11 UTC, aponcon-atolcd commented
For information, this PR is not about making a global configuration file for notifications. It will be addressed later (on another PR).

2021-03-31 11:54 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
> +	CONFIRMED_CASE_NOTIFICATIONS(true, true, null),
Rename to EVENT_PARTICIPANT_CASE_CONFIRMED_NOTIFICATIONS (very long, I know, but the current name sounds like it's associated to ALL notifications sent out when a case gets confirmed)

2021-03-31 11:54 UTC, MateStrysewske commented on SERVER_CUSTOMIZATION.md
> +* **Confirmed case related notifications** `CONFIRMED_CASE_NOTIFICATIONS`: Enables email and SMS notifications sent to the surveillance officer of events where a participant is a confirmed case
Change to:

``` 
**Notifications related to confirmed cases of event participants** `EVENT_PARTICIPANT_CASE_CONFIRMED_NOTIFICATIONS`: Enables email and SMS notifications sent to surveillance officers of events when the case of an event participant is confirmed
```

2021-03-31 11:54 UTC, MateStrysewske commented on SERVER_CUSTOMIZATION.md
> +* **Other notifications** `OTHER_NOTIFICATIONS`: Enables other email and SMS notifications (other than those impacted by `TASK_NOTIFICATIONS` and `CONFIRMED_CASE_NOTIFICATIONS` features)
CONFIRMED_CASE_NOTIFICATIONS => EVENT_PARTICIPANT_CASE_CONFIRMED_NOTIFICATIONS
Also, remove the "features" word at the end

2021-03-31 11:54 UTC, MateStrysewske requested changes
See comments above (forgot to click on Request changes :))

2021-04-01 11:08 UTC, MateStrysewske approved these changes

2021-04-01 11:08 UTC, merged