Management of event groups
hzi-braunschweig/SORMAS-Project pull request #4998
Opened 2021-04-06 14:48 UTC by aponcon-atolcd

Closes #4570 
Closes #4571 
Closes #4572 
Closes #4573 
Closes #4767

2021-04-09 13:19 UTC, MateStrysewske requested changes
Please make sure to NOT force-push your changes, but please do normal commits and pushes instead because force-pushes make it really, really hard for me to review those changes. Thank you!

2021-04-09 13:19 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java
> +		if (isGroupViewType()) {
What's the reason for removing and then retrieving the criteria again?

2021-04-09 13:19 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsView.java
> +		if (true)
Remove this

2021-04-09 13:19 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventSelectionField.java
> +		this.infoPickOrCreateEvent = I18nProperties.getString(Strings.infoPickOrCreateSuperordinateEventForEvent);
I guess that's not the correct I18n property because it references superordinate events

2021-04-09 13:19 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventExportDto.java
> +	private EventGroupsIndexDto eventGroups;
I think latest event group and event group count should be split in the export because that allows more flexibility with sorting

2021-04-09 13:19 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/groups/EventGroupsValueProvider.java
> +				+ HtmlHelper.buildTitle(String.format(I18nProperties.getCaption(Captions.eventGroupsSeveral), eventGroups.getCount()), "*")
See above, I'd prefer adding counts in brackets here instead of a *

2021-04-13 16:49 UTC, aponcon-atolcd commented
Hi @MateStrysewske 
Everything should be ok now
I've made other fixes too like the right management that were lacking when grouping events in bulk edit mode.

I've seen that the tests were no longer working. Seems to be unrelated to this PR thought as the exact same issue is occurring on another PR.

2021-04-14 14:23 UTC, MateStrysewske requested changes
Hey! Yes, the compile errors have been caused by us, they should be resolved if you merge the dev branch again. :)

The feature seems to work really well! Just a few remarks/things I've noticed:

* Linking an event from within an event group will not trigger the notification SMS/mail that the event has been added to an event group
* Right now, the list of events inside the notification always only contains one event (the event that was just added to/removed from the event group); that's fine by me, but I think it was defined slightly different in the corresponding issue (in that it should contain a list of all events currently in that group) - if it stays like right now, I'd suggest to change notification content and remove the list from the notification because it is a bit confusing; otherwise it would probably need to be fixed

2021-04-15 13:44 UTC, MateStrysewske requested changes
Right now, the only notifications that are actually sent (at least for me) are those when creating a new event group. Everything else - linking or unlinking events to/from existing event groups - does not send out notifications. Can you check that again please?

2021-04-15 14:33 UTC, aponcon-atolcd commented
@MateStrysewske 
There's a FeatureType (= EVENT_GROUPS_MODIFICATION_NOTIFICATIONS) related to notifications sent for Event Groups. But there was indeed an issue, the notification were related to the wrong FeatureType.
Now it is ok (if the FeatureType is enabled; it is not enabled by default).

2021-04-16 07:50 UTC, MateStrysewske requested changes
Oh yeah, sorry :D I had to temporarily remove the new feature configurations from my database again because I tested other stuff, and then I forgot to re-enable it when I checked out your PR again. Good thing though because it allowed you to find that minor bug :)

Tested it again, no further complains! Can you resolve the merge conflicts? I'll merge the PR afterwards.

2021-04-16 08:35 UTC, MateStrysewske approved these changes

2021-04-16 08:35 UTC, merged