#3936: Add a general comment field to person
hzi-braunschweig/SORMAS-Project pull request #5045
Opened 2021-04-12 12:58 UTC by ChristopherRiedel

closes #3936

2021-04-12 18:54 UTC, alexcaruntu-vita approved these changes

2021-04-19 10:31 UTC, MateStrysewske requested changes

2021-04-19 10:31 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java
> +	@Column(length = COLUMN_LENGTH_BIG)
We don't need column definitions in DTOs, move this to `Person` in sormas-backend instead and use annotation `@Column(columnDefinition = "text")`

2021-04-19 10:31 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
> +					currentVersion = 297;
Wrong `currentVersion` assignment, needs to be identical to the case

2021-04-19 10:31 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/person/Person.java
> +	@Column(length = COLUMN_LENGTH_BIG)
Use `@Column(columnDefinition = "text")` instead

2021-04-19 10:31 UTC, MateStrysewske commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +ALTER TABLE person ADD COLUMN additionaldetails varchar(4096);
Use `text` instead of varchar (same in the history table)

2021-04-20 08:27 UTC, MateStrysewske requested changes
* Add the @Column annotation to Person.java in sormas-backend
* Increase maxLines in the person edit fragment (mobile app) to 6
* Remove the maxLines parameter from the person read fragment (mobile app), otherwise it's impossible to display the whole text if it is too long

2021-04-20 22:55 UTC, syntakker commented
Removing `maxLines` in `ControlTextReadField` defaults to `maxLines = 2`, so `maxLine` is set to 4000 in the read field instead.

2021-04-21 07:52 UTC, MateStrysewske approved these changes

2021-04-21 07:52 UTC, merged