4851 reject labmessage
hzi-braunschweig/SORMAS-Project pull request #5077
Opened 2021-04-14 15:07 UTC by leventegal-she

Closes https://github.com/hzi-braunschweig/SORMAS-Project/issues/4851

2021-04-15 14:52 UTC, Alexandru-Pirvu requested changes

2021-04-15 14:52 UTC, Alexandru-Pirvu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageForm.java
> +import de.symeda.sormas.api.labmessage.LabMessageStatus;
Not used

2021-04-15 14:52 UTC, Alexandru-Pirvu commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
>  -- *** Insert new sql commands BEFORE this line ***
This should be deleted

2021-04-15 14:52 UTC, Alexandru-Pirvu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessagesGridComponent.java
> +public class LabMessagesGridComponent extends VerticalLayout {
Is this used?

2021-04-16 06:22 UTC, FredrikSchaeferVitagroup requested changes

2021-04-16 06:22 UTC, FredrikSchaeferVitagroup commented on sormas-api/src/main/resources/captions.properties
> +actionManualForwardLabMessage=Mark as manually forwarded
I find this slightly confusing. Actually, the lab message is just marked as forwarded, not as MANUALLY forwarded. The status makes no distinction between forwarded via S2S and manually forwarded. I would therefore suggest to change this to 
```suggestion
actionManualForwardLabMessage=Mark as forwarded
```

2021-04-16 06:22 UTC, FredrikSchaeferVitagroup commented on sormas-api/src/main/resources/strings.properties
> +confirmationManuallyForwardedLabMessage = Are you sure you want to mark this lab message as manually forwarded?
```suggestion
confirmationManuallyForwardedLabMessage = Are you sure you want to mark this lab message as forwarded?
```

2021-04-16 07:13 UTC, FredrikSchaeferVitagroup approved these changes

2021-04-16 07:15 UTC, merged