#4938 increase bulk-coordinate-setter performance
hzi-braunschweig/SORMAS-Project pull request #5127
Opened 2021-04-19 12:18 UTC by DavidBaldsiefen

This PR is supposed to improve the performance of the bulk-geocoordinate-setter (or more accurately: reduce the chance for timeouts). At it's core, the main change is that instead of using `getIndexList` a custom query using batched calls using `OFFSET` and `LIMIT` is used. It also only fetches each persons UUID instead of fetching the entire person.

It might make sense to add a cancel-button to the popup too, that is not yet done with this change.

Closes #4938

2021-04-19 13:32 UTC, StefanKock requested changes
Added two remarks, quickly fixable.

The approach looks better than before, but I'm uncertain if fetching the person UUIDs in 500 batch size is quicker than all at once. It the complex WHERE conditions are doing performance harm, the batching makes it worse.

2021-04-19 13:32 UTC, StefanKock commented on sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonsView.java
>  		// TODO disabled because of potential performance problems, see GitHub issue #4938
Remove comment

2021-04-19 13:32 UTC, StefanKock commented on sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java
> +		// The uuid-list is filtered by the users jurisdiction and retrieved in batches to avoid timeouts
Add empty line above

2021-04-19 13:53 UTC, DavidBaldsiefen commented
> Added two remarks, quickly fixable.
> 
> The approach looks better than before, but I'm uncertain if fetching the person UUIDs in 500 batch size is quicker than all at once. It the complex WHERE conditions are doing performance harm, the batching makes it worse.

I was also wondering what a good batch size would be. Another problem is that the user filter has some quite complex underlying cod (lots of joins etc.), which would also be re-executed each time.

2021-04-20 07:32 UTC, MateStrysewske approved these changes

2021-04-20 08:05 UTC, StefanKock approved these changes

2021-04-20 08:06 UTC, merged