#4175: Make event report date editable
hzi-braunschweig/SORMAS-Project pull request #5284
Opened 2021-04-29 16:18 UTC by ChristopherRiedel

Fixes #4175

2021-05-03 21:37 UTC, alexcaruntu-vita requested changes
Shouldn't all these be implemented for mobile app as well?

2021-05-05 12:50 UTC, ChristopherRiedel commented
> Shouldn't all these be implemented for mobile app as well?

true, I overlooked that

2021-05-12 08:45 UTC, DavidBaldsiefen commented on sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
> -				I18nProperties.getValidationError(Validations.beforeDate, quarantineFrom.getCaption(), quarantineTo.getCaption())));
Why is this done here?

2021-05-13 19:03 UTC, alexcaruntu-vita commented on sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java
> -				I18nProperties.getValidationError(Validations.beforeDate, quarantineFrom.getCaption(), quarantineTo.getCaption())));
Maybe by mistake. @ChristopherRiedel?

2021-05-13 19:04 UTC, alexcaruntu-vita approved these changes
I'm ok with all the changes. The PR can be merged after we clarify the question raised by @DavidBaldsiefen.

2021-05-14 08:13 UTC, merged