Add a link to the associated entity in Task notifications #4734
hzi-braunschweig/SORMAS-Project pull request #5299
Opened 2021-05-03 13:53 UTC by aponcon-atolcd

Fixes #4734

2021-05-07 12:14 UTC, BarnaBartha requested changes

2021-05-07 12:14 UTC, BarnaBartha commented on sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java
> +					String associatedEntityLinkMessagePart = getAssociatedEntityLinkMessagePart(context, associatedEntity);
extract these two additions (this and on line 744) that are the same to a method, for eg. appendAssociatedEntityLink(...)

2021-05-07 12:14 UTC, BarnaBartha commented on sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java
> +		return uiUrlBuilder.append("#!").append(taskContext.getUrlPattern()).append("/data/").append(uuid).toString();
this (being in the backend module) in combination with the TaskContext (api module) enum extension contain a non-typesafe dependency to the UI, and thus changes in the UI (or the complete change of the UI with the angular UI) can break this
Indeed having a solution for this is out of scope for this ticket but a comment would be good to at least increase the chances of not having an issue in the future

2021-05-11 08:09 UTC, MateStrysewske commented
@aponcon-atolcd Just a quick note, clicking on the small sync icon next to the reviewer's name in the top right requests a review from that person, which makes it easier for them to realise that the PR has been changed :) I suggest to have another look at the updated Contribution guidelines, there's a new section about pull requests in there that covers this topic among others

2021-05-11 10:11 UTC, merged