Add the possibility to disable Case and Contacts sub tabs from the configuration file #4733
hzi-braunschweig/SORMAS-Project pull request #5300
Opened 2021-05-03 14:00 UTC by aponcon-atolcd

Fixes #4733

2021-05-07 07:24 UTC, MateStrysewske requested changes
@aponcon-atolcd Hey! Sorry that I came up with this so late and that it causes additional work, but I think these configurations would be better suited for the featureconfiguration table in the database (given that they're basically true/false properties) - could you do that change? So basically add them as FeatureTypes instead, and then use the FeatureConfigurationFacade methods instead of the ConfigFacade (will also mean less code overall)

2021-05-12 08:09 UTC, MateStrysewske requested changes

2021-05-12 08:09 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
> +	VIEW_TAB_CASES_HOSPITALIZATION(false, true, null),
For all of the new feature types, set `serverFeature` to `true` and `dependentFeatures` to `new FeatureType[] { CASE_SURVEILANCE }` or `new FeatureType[] { CONTACT_TRACING }` respectively

2021-05-12 08:09 UTC, MateStrysewske commented on sormas-base/setup/sormas.properties
> +# Turn off theses properties to disable a tab in a Case view
These properties are no longer needed since they were moved to the FeatureType enum

2021-05-12 09:59 UTC, MateStrysewske requested changes
Web part looks good now, can you also adjust the Android app to no longer display these tabs if the feature configurations are turned off?

2021-05-12 13:07 UTC, aponcon-atolcd commented
@MateStrysewske Sorry, I totally forgot to manage the Android app. Should be good now!

2021-05-14 09:27 UTC, MateStrysewske approved these changes

2021-05-14 09:27 UTC, merged