Add recommended Android Studio JDK Version to README
hzi-braunschweig/SORMAS-Project pull request #5415
Opened 2021-05-12 08:36 UTC by DavidBaldsiefen

2021-05-12 09:03 UTC, StefanKock requested changes
1. In Step 3 there is not mentioned to also provide JDK 8. I think this should be added.
2. No ticket id in the commit?

2021-05-12 12:24 UTC, DavidBaldsiefen commented
>     1. In Step 3 there is not mentioned to also provide JDK 8. I think this should be added.

You mean adding info on where to get the JDK? This would depend on the user OS after all

>     2. No ticket id in the commit?

No ticket created, should I?

2021-06-30 09:42 UTC, MateStrysewske commented
@DavidBaldsiefen I think what Stefan means is that Step 3 only instructs the user to download Java 11, not Java 8, which would be necessary to properly set the JDK in Android Studio. The guide should be extended with that information as well.

And yes, please create a task issue for this and ammend the last commit you did to include the issue number.

2021-07-02 10:31 UTC, syntakker approved these changes

2021-07-02 10:32 UTC, merged