[#5671] deduplicate code in AbstractSormasToSormasInterface
hzi-braunschweig/SORMAS-Project pull request #5672
Opened 2021-06-04 11:36 UTC by JonasCir

Fixes #5671 

### Problem Description

This is a spin off from #5599, I want to keep the PRs small and easy to review.

While working on #5597, I noticed a lot of potential for code cleanup and deduplication which once resolved would make my life easier.

### Proposed Change

`AbstractSormasToSormasInterface` has code duplication and can be simplified for my work on #5597.

This unifies the handling of the received S2S entities. We have two cases:

1. An entity is newly shared and does not exists in the system ("sharing"). Code paths handling existing entities are ignored.
2. An entity already exists in the system ("returning" and "syncing"). Code paths handling existing entities are executed.

2021-06-07 09:06 UTC, leventegal-she requested changes
Instead of 3 similar methods you've introduced one that is a a 2in1 with duplicated if statments.

On the `decryptAndPersist` method I've added a suggestion for solving the 2in1 issue

2021-06-07 09:06 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
> +	private void persistNewEntities(SormasToSormasEncryptedDataDto encryptedData, Persister<P> persister)
This method is useless

2021-06-07 14:12 UTC, JonasCir commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
> +	private void persistNewEntities(SormasToSormasEncryptedDataDto encryptedData, Persister<P> persister)
true

2021-06-07 14:12 UTC, JonasCir commented on sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/AbstractSormasToSormasInterface.java
> +			existingEntities =
Totally right, results in much cleaner code

2021-06-07 14:13 UTC, JonasCir commented
@leventegal-she 
Thank you for the review, very good pointer how to remove the `existing` flag. Much cleaner now

2021-06-07 16:02 UTC, JonasCir commented
Rebased on accept reject

2021-06-08 06:23 UTC, leventegal-she approved these changes

2021-06-08 06:24 UTC, leventegal-she reviewed
Please check the test `SormasToSormasEventFacadeEjbTest.testSaveSyncedEvent` because it's failing in CI

2021-06-08 08:22 UTC, leventegal-she approved these changes

2021-06-08 08:27 UTC, merged