#5823: Join on case contact instead of subquery
hzi-braunschweig/SORMAS-Project pull request #6066
Opened 2021-07-05 11:31 UTC by StefanKock

Fixes #5823

2021-07-05 12:05 UTC, StefanKock commented
I tested the created SQL with `TaskFacadeEjbTest.testFilterTasksByUserJurisdiction`. The trimmed result is documented below, with `contacts52_` and `contacts55_` now directly joined.

Before:
```sql
-- ...
LEFT OUTER JOIN cases case51_ ON task0_.caze_id=case51_.id											 
LEFT OUTER JOIN Contact contact52_ ON task0_.contact_id=contact52_.id
LEFT OUTER JOIN cases case53_ ON contact52_.caze_id=case53_.id
-- ...
WHERE (task0_.creatorUser_id=?
-- ...
       OR case51_.id in
         (SELECT contact56_.caze_id
          FROM Contact contact56_
          WHERE contact56_.reportingUser_id=?
            OR contact56_.contactOfficer_id=?
            OR contact56_.region_id=? )
-- ...
       OR case53_.id in
         (SELECT contact57_.caze_id
          FROM Contact contact57_
          WHERE contact57_.reportingUser_id=?
            OR contact57_.contactOfficer_id=?
            OR contact57_.region_id=? )
-- ...
```

After:
```sql
LEFT OUTER JOIN cases case51_ ON task0_.caze_id=case51_.id
LEFT OUTER JOIN Contact contacts52_ ON case51_.id=contacts52_.caze_id
LEFT OUTER JOIN Contact contact53_ ON task0_.contact_id=contact53_.id
LEFT OUTER JOIN cases case54_ ON contact53_.caze_id=case54_.id
LEFT OUTER JOIN Contact contacts55_ ON case54_.id=contacts55_.caze_id

WHERE (task0_.creatorUser_id=?
-- ...
       OR contacts52_.reportingUser_id=?
       OR contacts52_.contactOfficer_id=?
       OR contacts52_.region_id=?
-- ...
       OR contacts55_.reportingUser_id=?
       OR contacts55_.contactOfficer_id=?
       OR contacts55_.region_id=?
-- ...
```

<details>
<summary>New complete compiled SQL</summary>

```sql
SELECT DISTINCT task0_.uuid AS col_0_0_,
                task0_.taskContext AS col_1_0_,
                case1_.uuid AS col_2_0_,
                person5_.firstName AS col_3_0_,
                person5_.lastName AS col_4_0_,
                event34_.uuid AS col_5_0_,
                event34_.eventTitle AS col_6_0_,
                event34_.disease AS col_7_0_,
                event34_.diseaseDetails AS col_8_0_,
                event34_.eventStatus AS col_9_0_,
                event34_.eventInvestigationStatus AS col_10_0_,
                event34_.startDate AS col_11_0_,
                contact12_.uuid AS col_12_0_,
                person16_.firstName AS col_13_0_,
                person16_.lastName AS col_14_0_,
                person18_.firstName AS col_15_0_,
                person18_.lastName AS col_16_0_,
                task0_.taskType AS col_17_0_,
                task0_.priority AS col_18_0_,
                task0_.dueDate AS col_19_0_,
                task0_.suggestedStart AS col_20_0_,
                task0_.taskStatus AS col_21_0_,
                user47_.uuid AS col_22_0_,
                user47_.firstName AS col_23_0_,
                user47_.lastName AS col_24_0_,
                task0_.creatorComment AS col_25_0_,
                user48_.uuid AS col_26_0_,
                user48_.firstName AS col_27_0_,
                user48_.lastName AS col_28_0_,
                task0_.assigneeReply AS col_29_0_,
                CASE
                    WHEN region2_.id IS NOT NULL THEN region2_.name
                    ELSE CASE
                             WHEN region13_.id IS NOT NULL THEN region13_.name
                             ELSE region36_.name
                         END
                END AS col_30_0_,
                CASE
                    WHEN district3_.id IS NOT NULL THEN district3_.name
                    ELSE CASE
                             WHEN district14_.id IS NOT NULL THEN district14_.name
                             ELSE district37_.name
                         END
                END AS col_31_0_,
                CASE
                    WHEN community4_.id IS NOT NULL THEN community4_.name
                    ELSE CASE
                             WHEN community15_.id IS NOT NULL THEN community15_.name
                             ELSE community38_.name
                         END
                END AS col_32_0_,
                CASE
                    WHEN (user47_.id IS NOT NULL)
                         AND user47_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                         OR (user48_.id IS NOT NULL)
                         AND user48_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                         OR 0=1
                         OR (user6_.id IS NOT NULL)
                         AND user6_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                         OR region7_.id=59
                         OR region8_.id=59
                         OR (user22_.id IS NOT NULL)
                         AND user22_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                         OR region23_.id=59
                         OR region20_.id=59
                         OR region21_.id=59
                         OR (user39_.id IS NOT NULL)
                         AND user39_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                         OR (user40_.id IS NOT NULL)
                         AND user40_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                         OR region42_.id=59 THEN 1
                    ELSE 0
                END AS col_33_0_,
                CASE
                    WHEN (case1_.id IS NOT NULL)
                         AND ((user9_.id IS NOT NULL)
                              AND user9_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                              OR region10_.id=59
                              OR region11_.id=59) THEN 1
                    ELSE 0
                END AS col_34_0_,
                CASE
                    WHEN (contact12_.id IS NOT NULL)
                         AND ((user28_.id IS NOT NULL)
                              AND user28_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                              OR region29_.id=59
                              OR region25_.id=59
                              OR region26_.id=59
                              OR (user27_.id IS NOT NULL)
                              AND user27_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                              OR region25_.id=59
                              OR region26_.id=59) THEN 1
                    ELSE 0
                END AS col_35_0_,
                CASE
                    WHEN (contact12_.id IS NOT NULL)
                         AND (case30_.id IS NOT NULL)
                         AND ((user31_.id IS NOT NULL)
                              AND user31_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                              OR region32_.id=59
                              OR region33_.id=59) THEN 1
                    ELSE 0
                END AS col_36_0_,
                CASE
                    WHEN (event34_.id IS NOT NULL)
                         AND ((user43_.id IS NOT NULL)
                              AND user43_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                              OR (user44_.id IS NOT NULL)
                              AND user44_.uuid='TN4D3A-3O4Z62-P64N5E-GMREKCFI'
                              OR region46_.id=59) THEN 1
                    ELSE 0
                END AS col_37_0_
FROM Task task0_
LEFT OUTER JOIN cases case1_ ON task0_.caze_id=case1_.id
LEFT OUTER JOIN Region region2_ ON case1_.region_id=region2_.id
LEFT OUTER JOIN District district3_ ON case1_.district_id=district3_.id
LEFT OUTER JOIN Community community4_ ON case1_.community_id=community4_.id
LEFT OUTER JOIN Person person5_ ON case1_.person_id=person5_.id
LEFT OUTER JOIN users user6_ ON case1_.reportingUser_id=user6_.id
LEFT OUTER JOIN Region region7_ ON case1_.responsibleRegion_id=region7_.id
LEFT OUTER JOIN Region region8_ ON case1_.region_id=region8_.id
LEFT OUTER JOIN users user9_ ON case1_.reportingUser_id=user9_.id
LEFT OUTER JOIN Region region10_ ON case1_.responsibleRegion_id=region10_.id
LEFT OUTER JOIN Region region11_ ON case1_.region_id=region11_.id
LEFT OUTER JOIN Contact contact12_ ON task0_.contact_id=contact12_.id
LEFT OUTER JOIN Region region13_ ON contact12_.region_id=region13_.id
LEFT OUTER JOIN Di [...]

2021-07-06 09:32 UTC, syntakker requested changes
Test `ContactFacadeEjbPseudonymizationTest.testPseudonymizeGetFollowupList` fails:
```
[ERROR] Errors: 
[ERROR]   ContactFacadeEjbPseudonymizationTest.testPseudonymizeGetFollowupList:265 ? IllegalState
```
Stacktrace:
```
java.lang.IllegalStateException: Duplicate key UPZOON-FX2HSH-UJKVX5-IMHY2AF4 (attempted merging values de.symeda.sormas.api.contact.ContactFollowUpDto@65ac2df3 and de.symeda.sormas.api.contact.ContactFollowUpDto@6d1dca90)

	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at de.symeda.sormas.backend.contact.ContactFacadeEjb.getContactFollowUpList(ContactFacadeEjb.java:958)
	at de.symeda.sormas.backend.contact.ContactFacadeEjb$ContactFacadeEjbLocal$Proxy$_$$_WeldSubclass.getContactFollowUpList(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
	at de.symeda.sormas.backend.contact.ContactFacadeEjb$ContactFacadeEjbLocal$Proxy$_$$_WeldSubclass.getContactFollowUpList(Unknown Source)
	at de.symeda.sormas.backend.contact.ContactFacadeEjb$ContactFacadeEjbLocal$Proxy$_$$_WeldClientProxy.getContactFollowUpList(Unknown Source)
	at de.symeda.sormas.backend.contact.ContactFacadeEjbPseudonymizationTest.testPseudonymizeGetFollowupList(ContactFacadeEjbPseudonymizationTest.java:265)
...
```

2021-07-07 07:28 UTC, syntakker commented
A pattern similar to the cause of the failing test `ContactFacadeEjbPseudonymizationTest.testPseudonymizeGetFollowupList` (fixed in https://github.com/hzi-braunschweig/SORMAS-Project/pull/6066/commits/89837cde0dab64d622cbf05a4d47ebe6b5c138d0 can be found in:

CaseFacadeEjb.getCaseFollowUpList (l. 3404)

This query's results should be distinct, too.

2021-07-07 12:58 UTC, syntakker approved these changes

2021-07-07 13:02 UTC, merged