Feature 6025 travel entry forms
hzi-braunschweig/SORMAS-Project pull request #6165
Opened 2021-07-20 07:10 UTC by sergiupacurariu

Fixes #6025

2021-07-20 09:35 UTC, MateStrysewske requested changes
* Deleted travel entries still appear in the directory - could you fix that in this PR please?
* Same for archived entries; there also needs to be a dropdown to toggle between archived, active and all entries (as for other directories)
* Some of the fields only have a very small width (see screenshot below)
* Checking "point of entry jurisdiction differs from responsible jurisdiction" copies the responsible district over to the point of entry district, but not the region (either both or none are fine); moreover, when deselecting it again, the point of entry is removed as well and can no longer be selected because it apparently still relies on the empty point of entry region and district fields instead of the responsible jurisdiction fields (both in the create and edit forms)
* The "Land" and "Risikoklasse" fields are not saved, i.e. not written to the database; might have something to do with the captions being not unique, but I don't think it's a database problem because it works when importing data

![image](https://user-images.githubusercontent.com/23701005/126291841-0e09f9f1-84e5-4516-9a79-463bdac82e4f.png)

2021-07-20 10:36 UTC, sergiupacurariu commented on sormas-api/src/main/java/de/symeda/sormas/api/Disease.java
> +	public static List<Disease> IN_DISEASE_LIST = Arrays.asList(Disease.values());
changed to "DISEASE_LIST"

2021-07-20 10:38 UTC, sergiupacurariu commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +INSERT INTO schema_version (version_number, comment) VALUES (386, 'DEA Travel entry form #6025');
updated the message including the recommended message

2021-07-20 10:40 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntriesView.java
> +			List<String> travelEntries = FacadeProvider.getTravelEntryFacade().getAllUuids();
changed to count method

2021-07-20 10:41 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java
> +//		if (person == null || disease == null) {
removed

2021-07-20 10:45 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java
> +		addField(de.symeda.sormas.api.travelentry.TravelEntryDto.REPORT_DATE, DateField.class);
update all of them in the class

2021-07-20 10:54 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/travelentry/TravelEntryDataForm.java
> +		}
rewrite the logic

2021-07-21 10:29 UTC, MateStrysewske requested changes
- [x] Change captions of the "All", "Active" and "Archived" options to "All travel entries", "Archived travel entries", etc. (instead of "... cases")
- [ ] The dropdown is always cleared when entering the view, even though the previous (or default) selection applies; the selection should be displayed in the dropdown
- [ ] Reload the travel entry list after importing
- [x] Interestingly, I still have one case where the text field only takes part of the available width

2021-07-21 13:16 UTC, MateStrysewske approved these changes

2021-07-21 13:36 UTC, merged