Add specific risks property into events #5940
hzi-braunschweig/SORMAS-Project pull request #6185
Opened 2021-07-22 07:54 UTC by aponcon-atolcd

Fixes #5940

2021-07-27 12:17 UTC, MateStrysewske requested changes
I would suggest to call the new enum `SPECIFIC_EVENT_RISK` to make the context clearer. Can you do the necessary changes please?

2021-07-27 12:17 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/customizableenum/CustomizableEnumFacade.java
> +	<T extends CustomizableEnum> List<T> getEnumValues(CustomizableEnumType type);
I don't think this method is necessary; you should simply be able to call getEnumValues(CustomizableEnumType, Disease) with disease == null instead. This new logic actually makes the diseases column unusable, but there might be cases in the future in which people want to associate a specific risk with a specific disease for whichever reason.

2021-07-27 12:17 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/customizableenum/CustomizableEnumValueDao.java
> +	public <T extends CustomizableEnum> List<T> getEnumValues(CustomizableEnumType type) {
See above, use the method with the disease parameter instead and pass null as the disease

2021-07-27 12:17 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/event/edit/EventEditFragment.java
> +		}
Make sure to not show the new field when there are no entries in the database; see CaseEditFragment.updateDiseaseVariantsField. You don't have to move the code to a dedicated method, just make sure that the visibility logic is executed (probably best to do that in onLayoutBinding)

2021-07-29 14:06 UTC, MateStrysewske requested changes
* Don't show the "Other specific risk" column if there are no entries in the database
* The new field is still displayed in the mobile app, both in the read and edit forms, when there are no entries in the database

2021-07-30 12:19 UTC, aponcon-atolcd commented
Hi @MateStrysewske Thanks for the review.

Indeed it was not ok at all, I'm sorry about that. Should be better now. :)

2021-07-30 13:02 UTC, MateStrysewske commented
@aponcon-atolcd Thanks! I'll merge your PR now because I'm aware that you won't be able to work on it next week. There's still something that needs to be done, i.e. changing the disease of an event also needs to trigger a reload of the potential event risks, and to be consistent with the disease variants, we should not show the new field in read fragments in the mobile app at all when it's not filled in, but I will implement that myself.

2021-07-30 13:04 UTC, MateStrysewske approved these changes

2021-07-30 13:04 UTC, merged