[#6696] use nil UUID for region, district, community
hzi-braunschweig/SORMAS-Project pull request #6707
Opened 2021-09-15 09:50 UTC by JonasCir

Fixes #6696 
This is intentionally leaving out point of entry and facility. This is because they are (not yet included) in central, meaning UUIDs of these two types will also vary in the wild. To mimic this behavior while testing, both of the corresponding default entities will have random UUIDs.

2021-09-15 13:33 UTC, JonasCir commented
This seems to trigger an issue with the default users

2021-09-15 14:17 UTC, JonasCir commented
Martin had some comments about using a seed to generate different UUIDs. Will take care of it tomorrow + I found some issues with the default users which I'm going to fix here as well.

2021-09-16 12:45 UTC, JonasCir commented
This is now ready for review. I created an enum and use the ordinal values of each variant to generate the corresponding UUID. By this we can arbitrary extend the enum (e.g., `SECOND_DEFAULT_REGION`) and we will also get a constant UUID for it.

2021-09-20 10:23 UTC, MartinWahnschaffe requested changes
Just one rename - afterwards you can merge it.

2021-09-20 10:23 UTC, MartinWahnschaffe commented on sormas-api/src/main/java/de/symeda/sormas/api/utils/DefaultEntityHelper.java
> +	public enum Infrastructure {
Better DefaultInfrastructureUuidSeed

2021-09-20 10:40 UTC, merged