Bugfix 6715 task reassignment android
hzi-braunschweig/SORMAS-Project pull request #6847
Opened 2021-09-30 11:37 UTC by syntakker

Fixes #6715

2021-09-30 12:26 UTC, MateStrysewske requested changes

2021-09-30 12:26 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
> +			// TODO roles? what happens when there are no supervisors? assignee user cannot be null
Please have a look at the task assignment process in the onCaseChanged method in the web backend and adjust the task assignment here accordingly, i.e. when there is no officer assigned to the case, use a random officer from the responsible district or, if there's none, from the place of stay district before falling back to supervisors.

2021-09-30 12:26 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
>  				|| (changedCase.getResponsibleDistrict() == null && !DataHelper.isSame(changedCase.getDistrict(), existingCase.getDistrict()))) {
This code does not apply to the current logic anymore; the responsible district of a case can never be null. Also, please make sure to ONLY re-assign the surveillance officer of the case here if the current responsible officer's district is NEITHER the responsible district NOR the place of stay district anymore

2021-10-01 09:06 UTC, MateStrysewske requested changes

2021-10-01 09:51 UTC, syntakker commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
> +				|| (responsibleDistrictChanged
done.

2021-10-01 10:06 UTC, MateStrysewske approved these changes

2021-10-01 10:06 UTC, merged