Feature 7148 reduced immunizations backend logic
hzi-braunschweig/SORMAS-Project pull request #7228
Opened 2021-11-11 11:40 UTC by MateStrysewske

Fixes #7148

2021-11-11 16:02 UTC, MartinWahnschaffe requested changes

2021-11-11 16:02 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/vaccination/VaccinationFacadeEjb.java
> +		// If the vaccination date is empty, add the vaccination to the latest immunization
Suggestion: Add something like "Case 1: ..." to these 4 comments and then make sure that every case is covered in the unit test (add comments there as-well).

2021-11-12 09:07 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
> +		if (featureConfigurationFacade.isFeatureEnabled(FeatureType.IMMUNIZATION_STATUS_AUTOMATION)
I'll add the information to the Wiki page when 1.66 has been released.

2021-11-12 13:26 UTC, MartinWahnschaffe approved these changes

2021-11-12 13:28 UTC, merged