Feature 7434 do not validate case save from visit
hzi-braunschweig/SORMAS-Project pull request #7556
Opened 2021-12-21 12:42 UTC by BarnaBartha

Fixes #

2021-12-22 09:36 UTC, MateStrysewske requested changes
You would've spared yourself a lot of refactoring work by adding a second `saveCase` method with the additional parameter, and by extending the current method to call the new method with `false` :) I'd suggest to still do this because it makes the code a lot cleaner (i.e. far less unnecessary parameters).

2021-12-22 15:03 UTC, BarnaBartha commented
Actually the IDE changed the signature automatically so no trouble there.
But I do agree that exposing it that way shows the actual problem in an enhanced way, that there is no true separation or the concept of system action vs user action. It is a specific flag for this scenario, and after some time a similar flag will appear for another entity's saving/validation logic and we'll just increase the unnecessary logic that complicates developers lives later as we never truly fix these issues.

2022-01-03 08:31 UTC, MateStrysewske requested changes

2022-01-03 08:31 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +		return saveCase(dto, true, true, false, false);
`internal` should not be set to false here; see line 1455, the method there sets it to `true` as well. If I understand it correctly, `internal` should always be true unless the case comes from an external source (e.g. sormas2sormas). I suggest to ommit the argument here and let the saveCase method in 1455 handle it.

2022-01-03 08:31 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +		return saveCase(dto, true, true, false, systemSave);
Same here

2022-01-03 08:31 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +		saveCase(leadCaseData, !cloning, true, false, false);
Same here

2022-01-03 08:31 UTC, MateStrysewske commented on sormas-rest/src/main/java/de/symeda/sormas/rest/CaseResource.java
> +		return savePushedDto(dtos, dto -> FacadeProvider.getCaseFacade().saveCase(dto));
Strange refactoring - the `::` notation should actually be the preferred one by the IDE

2022-01-06 09:54 UTC, MateStrysewske approved these changes

2022-01-06 09:55 UTC, merged