Change/7530 enable sync when locked
hzi-braunschweig/SORMAS-Project pull request #7590
Opened 2022-01-04 13:25 UTC by JonasCir

Fixes #7530 

This PR does introduces:
* a `saveUnchecked` method which allows central to store data despite it being locked for the user
* moves the `save` and `saveUnchecked` methods completely to the `AbstractInfrastructureEjb`
* Fixes a couple (read: a lot) of warnings regarding constant usage while I was at it :)
* `save` for `Country`  has been transformed into generic code. If you compare the previous code to the `save` method in the `AbstractInfrastructureEjb`, you see it was almost identical. The validation check for the iso code is not necessary anymore as we have a `@Valid` annotation at the `ADO` now . The `findDuplicates` method has been updated accordingly.

2022-01-05 11:09 UTC, MateStrysewske requested changes
Had a first look at the code, but didn't test the changes yet because there are test failures. Please fix those. :)

2022-01-07 10:26 UTC, JonasCir commented
@MateStrysewske I'm off for today, but this needs to go in the next release, you can take care of merging it when reviewed?

2022-01-07 10:27 UTC, MateStrysewske commented
@JonasCir Will do so :)

2022-01-10 09:34 UTC, MateStrysewske requested changes
```
org.glassfish.deployment.common.DeploymentException: CDI definition failure:HV000152: Two methods defined in parallel types must not declare parameter constraints, if they are overridden by the same method, but methods InfrastructureBaseFacade#saveUnchecked(EntityDto) and AbstractInfrastructureEjb#saveUnchecked(InfrastructureDto) both define parameter constraints. -- HV000152: Two methods defined in parallel types must not declare parameter constraints, if they are overridden by the same method, but methods InfrastructureBaseFacade#saveUnchecked(EntityDto) and AbstractInfrastructureEjb#saveUnchecked(InfrastructureDto) both define parameter constraints.
	at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessAnnotatedType(ContainerLifecycleEvents.java:189)
	at org.jboss.weld.bootstrap.events.ContainerLifecycleEvents.fireProcessAnnotatedType(ContainerLifecycleEvents.java:173)
	at org.jboss.weld.bootstrap.BeanDeployer.processAnnotatedTypes(BeanDeployer.java:166)
	at org.jboss.weld.bootstrap.BeanDeployment.createTypes(BeanDeployment.java:219)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:421)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
	at org.glassfish.weld.WeldDeployer.processApplicationLoaded(WeldDeployer.java:510)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:424)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:344)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:568)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:561)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:564)
	at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:251)
	at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:166)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]
```

2022-01-10 10:54 UTC, JonasCir commented
ah I hate this :D

2022-01-11 08:29 UTC, JonasCir commented
@MateStrysewske This issue you found is actually unrelated to my PR, I noticed that `@Valid` annotation is not triggered consistently (I found at least two cases where it is possible to save invalid data, and one case where it appears to run non-determnistic). This issue is much bigger than this PR.

2022-01-11 09:02 UTC, MateStrysewske commented
@JonasCir The messages are correctly caught and displayed in the error log on the development branch though

2022-01-11 11:06 UTC, JonasCir commented
Yes they are, but this mechanism relies on the exception thrown by the ORM if a DB constraint was violated, not on the actual validation logic if I'm not mistaken.
I'm going to reintroduce the custom exception for now.

2022-01-11 12:42 UTC, JonasCir commented
To test this,  you might need to get rid of your ./m2 cache in your home directory to test it reliably :)

2022-01-11 13:14 UTC, JonasCir commented
@MateStrysewske ready for review, I tested the csv import and it generates the error import again.

2022-01-12 09:15 UTC, MateStrysewske approved these changes

2022-01-12 09:15 UTC, merged