Added a testing scenario for Event
hzi-braunschweig/SORMAS-Project pull request #7795
Opened 2022-01-27 11:52 UTC by mk-sgent

2022-01-27 11:53 UTC, mk-sgent commented
![EventPicturefozRazvan](https://user-images.githubusercontent.com/97879405/151353929-e1264bdf-ea6f-47b8-bf45-158621f3f416.PNG)

2022-01-28 09:31 UTC, rdutu-vg requested changes

2022-01-28 09:31 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/api/PersonSteps.java
> +          System.out.println("Year of Birth" + createPersonObject.getBirthdateYYYY().toString());
remove

2022-01-28 09:31 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
> +        "I select Risk level filter {string} among the filter options",
mention also page llocation

2022-01-28 09:31 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
> +          // String sourceTypeOfPlace = apiState.getCreatedEvent().getTypeOfPlace();
remove commented and add location in bdd name

2022-01-28 09:31 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/PersonDirectorySteps.java
> +                        "Number of displayed cases is not correct")));
persons not cases

2022-01-31 14:59 UTC, rdutu-vg approved these changes

2022-01-31 15:00 UTC, merged