Added test scenario for Persons Form Card navigtion
hzi-braunschweig/SORMAS-Project pull request #7938
Opened 2022-02-09 14:01 UTC by mp-sgent

2022-02-09 14:14 UTC, mp-sgent commented
![image](https://user-images.githubusercontent.com/96250118/153218728-e169b6df-2167-4e0d-8fad-b73fc4c6ad32.png)

2022-02-23 14:20 UTC, rdutu-vg requested changes

2022-02-23 14:20 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/EditPersonPage.java
> +  public static final By EDIT_CASES = By.id("edit-case-0");
please add also an identifier  _BUTTON _ICON etc, something to understand exactly which element is in UI

2022-02-23 14:20 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/persons/EditPersonPage.java
> +  public static final By EDIT_CONTACTS = By.id("edit-contact-0");
same as above

2022-02-23 14:20 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
> +        "I click on Edit Immunization button from Immunization card on Edit Person page",
let's mention also that the action is performed for the immunization created via API, so we can differenciate it from other immunizations which can be created in UI flows in other steps/pages

2022-02-23 14:20 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/resources/features/sanity/web/Persons.feature
> +  Scenario: Form card navigation in Edit Person Directory
please rename it to reflect a relevant test

2022-03-01 08:51 UTC, mp-sgent commented
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/56/allure/

2022-03-01 11:28 UTC, rdutu-vg approved these changes

2022-03-01 12:17 UTC, merged