SORQA-39 Enter an exposure data in Case Directory
hzi-braunschweig/SORMAS-Project pull request #8061
Opened 2022-02-18 15:24 UTC by mk-sgent

![image](https://user-images.githubusercontent.com/97879405/154711001-db14bda8-f618-4412-9225-302191f5c6de.png)

2022-02-23 12:42 UTC, rdutu-vg requested changes

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/ContinentUUIDs.java
> +  public static String getRandomContinentUUIDsName() {
please remove, there is only one continent for now so we don't need this

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/CountryUUIDs.java
> +  public static String getRandomCountryUUIDsName() {
same as above

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/DistrictsValues.java
> +  public static String getRandomDistrictsValuesName() {
same

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/RegionsValues.java
> +  public static String getRandomRegionsValuesName() {
same

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/SubcontinentUUIDs.java
> +  public static String getCaptionFor(String option) {
this needs to be refactored everywhere

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/enums/TypeOfActivity.java
> +public enum TypeOfActivity {
we already have:
**public enum ActivityTypes**
Please rename new created to reflect the need, and update also the existing one

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java
> +  public static final By CASES_EPIDEMIOLOGICAL_DATA = By.cssSelector("#tab-cases-epidata");
rename it accordingly

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/cases/CaseDirectoryPage.java
> +  public static final By CASES_NEW_ENTRY_EPIDEMIOLOGICAL_DATA = By.id("actionNewEntry");
rename it accordingly

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java
> +  public static final By CONTACT_EPIDEMIOLOGICAL_DATA = By.cssSelector("#tab-contacts-epidata");
rename it accordingly

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java
> +  public static final By NEW_ENTRY_EPIDEMIOLOGICAL_DATA = By.id("actionNewEntry");
rename it accordingly

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java
> +  public static final By CASE_LIKE = By.id("contactOrCaseLike");
rename it accordingly

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/ContactDirectoryPage.java
>    public static final By EPIDEMIOLOGICAL_DATA_TAB = By.cssSelector("#tab-contacts-epidata");
please review all locators and rename them to refelct the WebElement type. So the ending should reflect the item in UI (eg: button, input, tab etc)

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/services/ContactService.java
> +  public Exposure buildGeneratedExposureDataContactForRandomInputs() {
what do you mean random inputs? what's the need of this method?

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/CaseDirectorySteps.java
> +        "I select Type of activity except Gathering and Other options from Combobox in Exposure form",
if we perform one action, why do we involve in the bdd sentence other items?

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
> +          webDriverHelpers.clickOnWebElementBySelector(DONE_BUTTON);
move out this action so we can reuse it after

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
> +          webDriverHelpers.clickOnWebElementBySelector(DONE_BUTTON);
same

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
> +        "I fill Location form for Type of place by Other option",
this method actually generates some random data and fills 1 field.
I don't see the need of building a new DTO only to update one field value.

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
> +        "I fill a Type of activity details in Exposure by ([^\"]*) TEXT",
do we need the TEXT keyword?

2022-02-23 12:42 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/ContactDirectorySteps.java
> +        "I fill a type of gathering details in Exposure form by ([^\"]*) TEXT",
same

2022-02-23 12:43 UTC, rdutu-vg commented
There are changes which can cause failures into multiple tests.
Please address them, then aside test passing proof, attach also a regression run.

2022-03-24 10:41 UTC, jp-sgent commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java
> +    //        });
I don't think we should be committing commented-out code.

2022-03-24 10:41 UTC, jp-sgent commented on sormas-e2e-tests/src/test/resources/features/sanity/web/EpidemiologicalDataCase.feature
> +    And I fill Location form for Type of place field by "Unbekannt" options in Case directory for DE version
We were instructed not to use a different language in step definitions - even as a parameter.
This applies to all german words below as well.

2022-03-24 13:44 UTC, rdutu-vg commented
@mk-sgent please run also a regression over this branch to check how stable are the changes

2022-03-26 10:05 UTC, mk-sgent commented
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/501/allure/

![JobsForSorqa-39](https://user-images.githubusercontent.com/97879405/160234711-6a8218e8-d824-4ed8-a3ef-781bbb07029e.PNG)

2022-03-28 09:33 UTC, rdutu-vg approved these changes

2022-03-28 09:33 UTC, merged