Bug/8017 disease users can be associated to entities related to other diseases
hzi-braunschweig/SORMAS-Project pull request #8230
Opened 2022-03-04 09:20 UTC by dinua

Fixes #

2022-03-04 11:01 UTC, MateStrysewske commented
@dinua Please make sure to connect your PRs with the respective issue by adding the issue number to the PR description (so, in this case, it would be "Fixes #8017") - this way, the automation will make sure that when a PR is merged, the connected issue is closed and automatically moved to the Testing lane. :)

2022-03-10 16:24 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java
> +			items.addAll(FacadeProvider.getUserFacade().getUsersByRegionAndRoles(region, null, UserRole.SURVEILLANCE_SUPERVISOR));
how ResponsibleUser filter will work on events since we know that on an event the disease is not mandatory

2022-03-10 16:24 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java
> +				FacadeProvider.getUserFacade().getUsersByRegionAndRoles(region, null, UserRole.SURVEILLANCE_SUPERVISOR, UserRole.SURVEILLANCE_OFFICER));
same here: how Responsible User filter will work?

2022-03-23 10:47 UTC, sergiupacurariu requested changes

2022-03-23 10:47 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java
> +			if (selectedDiseases.size() == 1) {
please review this logic, it does not seem to work when multiple cases having the same disease are selected

2022-03-23 14:08 UTC, merged