Qu auto/sorqa 21 fixes
hzi-braunschweig/SORMAS-Project pull request #8334
Opened 2022-03-10 16:50 UTC by mk-sgent

2022-03-10 17:08 UTC, mk-sgent commented
**First**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/281/allure/#suites/e3855a0684872376b20823296a513beb/4dfc4f5de95f9028/
**Second**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/282/allure/#suites/e3855a0684872376b20823296a513beb/d1d4e62bfd8eb319/

2022-03-21 07:03 UTC, rdutu-vg requested changes

2022-03-21 07:03 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EventDirectoryPage.java
> +      By.xpath(
no.. this type of locator is not accepted. If a developer will change any div from that nest, we'll have to fix it again.

2022-03-22 14:04 UTC, rdutu-vg approved these changes

2022-03-22 23:28 UTC, rdutu-vg approved these changes

2022-03-22 23:28 UTC, merged