#8132 create person when creating a new case or a new contact
hzi-braunschweig/SORMAS-Project pull request #8367
Opened 2022-03-13 18:47 UTC by marius2301

Fixes #

2022-03-18 12:41 UTC, MateStrysewske requested changes

2022-03-18 12:41 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CoreAndPersonDto.java
> +	public CoreAndPersonDto(PersonDto person, T coreData) {
Constructors should be above the getters

2022-03-18 12:41 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactAndPersonDto.java
> +public class ContactAndPersonDto extends ContactDto {
I believe this class is no longer needed?

2022-03-18 12:41 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java
> +		if (dto instanceof ContactAndPersonDto) {
This code is probably no longer needed

2022-03-18 12:41 UTC, MateStrysewske commented on sormas-rest/src/main/java/de/symeda/sormas/rest/CaseResource.java
> +	@Path("/post")
Please rename the endpoint to `pushWithPerson` (to be in line with the existing POST endpoint)

2022-03-18 12:41 UTC, MateStrysewske commented on sormas-rest/src/main/java/de/symeda/sormas/rest/ContactResource.java
> +	@Path("/post")
Same as above

2022-03-21 13:44 UTC, MateStrysewske approved these changes

2022-03-21 13:45 UTC, MateStrysewske requested changes
Merge conflicts :) looks good otherwise

2022-03-22 06:47 UTC, BarnaBartha approved these changes

2022-03-22 07:45 UTC, merged