[#8025] add interceptors
hzi-braunschweig/SORMAS-Project pull request #8370
Opened 2022-03-14 09:28 UTC by JonasCir

Fixes #8025

2022-03-17 11:30 UTC, JonasCir commented
@MartinWahnschaffe 
A couple of small todos left, but overall good for a fist pass :)

2022-03-21 11:45 UTC, JonasCir commented
@MartinWahnschaffe This is as optimized as it gets for now. We have a dedicated fast path for this feature if disabled. When enabled, I did not witness any noticeable loss of performance.

2022-03-21 13:01 UTC, MartinWahnschaffe requested changes

2022-03-21 14:00 UTC, JonasCir commented on sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLogger.java
> +			loggingDisabled = true;
done

2022-03-21 14:00 UTC, JonasCir commented on sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerInterceptor.java
> +			ignoreLocalAnnotatedClasses.add(target);
fixed

2022-03-21 14:52 UTC, MartinWahnschaffe approved these changes

2022-03-22 10:45 UTC, merged