Feature 7713 history delete triggers
hzi-braunschweig/SORMAS-Project pull request #8434
Opened 2022-03-18 08:13 UTC by BarnaBartha

Fixes #7713

2022-03-22 10:14 UTC, MateStrysewske approved these changes
Looks fine to me, but I shouldn't do the final evaluation here. @MartinWahnschaffe please also have a look over this.

2022-03-22 13:35 UTC, MartinWahnschaffe commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +    BEFORE INSERT OR UPDATE ON contacts_visits
This may still have to trigger on deletion. Let's discuss

2022-03-23 10:06 UTC, MartinWahnschaffe requested changes

2022-03-23 10:06 UTC, MartinWahnschaffe commented on sormas-backend/src/test/resources/checkHistoryTables.sql
>  ORDER BY remark, table_name , column_name;
Let's also include this check:

```suggestion
UNION
SELECT 'invalid versioning trigger' as remark, t.table_name, null as column_name, 'DELETE' as data_type FROM information_schema."tables" t
WHERE t.table_schema = 'public'
  AND NOT (t.table_name ~* '_')
  AND t.table_name NOT LIKE '%_history'
  AND t.table_name NOT IN ('schema_version', 'systemevent')
  AND t.table_name NOT like 'pg_%'
  AND exists(SELECT trigger_name
                 FROM information_schema.triggers
                 WHERE trigger_name = 'versioning_trigger'
                   AND (event_manipulation = 'DELETE')
                   AND event_object_table = t.table_name)
ORDER BY remark, table_name , column_name;
```

2022-03-23 14:42 UTC, alexcaruntu-vita approved these changes

2022-03-24 15:16 UTC, BarnaBartha commented
@MartinWahnschaffe i need some help/input here
the failing test is the testHistoryTablesMatch() - i don't understand why but it behaves differently within the container than on the local instance (both with old and new clean db)
can you please check it?

2022-03-25 11:56 UTC, merged