Qu auto/sorqa 95
hzi-braunschweig/SORMAS-Project pull request #8460
Opened 2022-03-21 09:47 UTC by mk-sgent

2022-03-21 09:52 UTC, jp-sgent approved these changes

2022-03-21 11:04 UTC, mk-sgent commented
![SORQA-95](https://user-images.githubusercontent.com/97879405/159248799-261d2bfe-ab9e-4042-b4bc-b29123e03451.PNG)

2022-03-21 11:05 UTC, mk-sgent commented
**First**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/387/allure/
**Second**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/388/allure/

2022-03-21 14:01 UTC, pk-sgent approved these changes

2022-03-22 12:05 UTC, rdutu-vg requested changes

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +    When(
this method is not working. You have a switch, but there's no parameter passed there.

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +        "^I read data from downloaded XLSX file$",
be more specific because we have multiple XLSX downloaded files

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +        "I detect language for XLSX file content",
here you say detect, but you also perform checks. Please rename it to refactor the purpose of the actions, and which language are we checking there?

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +          File toDelete =
wrap in try catch blocks, so we can catch if there is any I/O exception

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +  public static void ReadXlsxFile() {
private

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +  public static void ReadXlsxFile() {
camelcase for methods

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +
remove space

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +      e.printStackTrace();
use log to expose this, otherwise we can't see it

2022-03-22 12:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +      e.printStackTrace();
same as above

2022-03-24 11:37 UTC, rdutu-vg requested changes

2022-03-24 11:37 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +      log.error("The exception occurred" + e + "The xlsx file couldn't be read");
log.error("Exception caught: {}", e);

2022-03-24 11:37 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/AboutDirectorySteps.java
> +          File toDelete =
can't see this adddressed

2022-03-24 11:37 UTC, rdutu-vg commented
@mk-sgent add also a check that the language has been changed after to see it, and run it again in jenkins to see the last screenshot

2022-03-26 09:06 UTC, mk-sgent commented
The last screenshot from Jenkins that ensure back language to English:

![LanguageCheck](https://user-images.githubusercontent.com/97879405/160232665-be128bac-803c-482e-8ca6-8a56dfc72439.PNG)

2022-03-31 08:59 UTC, rdutu-vg approved these changes

2022-03-31 08:59 UTC, merged