Change 8318 replace user roles android app
hzi-braunschweig/SORMAS-Project pull request #8583
Opened 2022-03-28 13:53 UTC by MateStrysewske

Fixes #8318

2022-03-28 13:54 UTC, MateStrysewske commented
@ChristopherRiedel Since you've worked on the replacement of user roles in the web app, I think it makes sense that you do the review of this PR. :)

2022-04-08 12:33 UTC, ChristopherRiedel requested changes

2022-04-08 12:33 UTC, ChristopherRiedel commented on sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java
> +		if (user.getPointOfEntry() != null) {
user.hasJurisdictionLevel(JurisdictionLevel.POINT_OF_ENTRY) && user.getPointOfEntry() != null

2022-04-08 14:18 UTC, ChristopherRiedel commented on sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java
> +		if (user.getPointOfEntry() != null) {
true

2022-04-08 14:22 UTC, ChristopherRiedel approved these changes

2022-04-11 04:55 UTC, merged