Bugfix 8550 followup date in case created from contact
hzi-braunschweig/SORMAS-Project pull request #8591
Opened 2022-03-29 07:06 UTC by alexcaruntu-vita

Fixes #8550

2022-03-31 13:50 UTC, MateStrysewske requested changes

2022-03-31 13:50 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +			Date untilDate = service.computeFollowUpuntilDate(caze, contact.getSamples());
Remove the unnecessary variable declaration and pass `computeFollowUpuntilDate` directly to `setFollowUpUntil`

2022-03-31 14:15 UTC, alexcaruntu-vita commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +			Date currentFollowUpUntil = caze.getFollowUpUntil();
I have moved it above to preserve the intent of the previous code.

2022-04-01 09:42 UTC, MateStrysewske approved these changes

2022-04-01 09:42 UTC, merged