[#8602] enforce https where possible
hzi-braunschweig/SORMAS-Project pull request #8604
Opened 2022-03-29 12:09 UTC by JonasCir

Fixes #8602 
Fixes https://github.com/hzi-braunschweig/SORMAS-Security/issues/36
Fixes https://github.com/hzi-braunschweig/SORMAS-Security/issues/35

2022-04-01 14:29 UTC, JonasCir commented
Should be in the release notes

2022-04-04 09:41 UTC, MateStrysewske requested changes

2022-04-04 09:41 UTC, MateStrysewske commented on sormas-backend/src/test/java/de/symeda/sormas/backend/common/ConfigFacadeEjbTest.java
> +		}catch (IllegalArgumentException ignored){}
Code formatting - otherwise everything looks fine to me.

2022-04-08 13:33 UTC, vidi42 approved these changes

2022-04-08 13:40 UTC, merged