Added German version of Event Directory Filter test
hzi-braunschweig/SORMAS-Project pull request #8632
Opened 2022-03-30 14:07 UTC by jp-sgent

https://jira.sormas-tools.de/browse/SORQA-137

2022-03-30 14:14 UTC, pk-sgent approved these changes

2022-03-31 08:47 UTC, rdutu-vg requested changes

2022-03-31 08:47 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
> +        "I select random German Risk level filter among the filter options from API",
"filter options from API"

please adjust the method name to reflect that we select the risk level based on the value set in the Event created by API

2022-03-31 08:47 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
> +        "I select German Type of Place field among the filter options from API",
same as above comment

2022-04-01 12:44 UTC, rdutu-vg approved these changes

2022-04-01 12:44 UTC, merged