SORQA-150 Stabilize "Add a task from contact and verify the fields"
hzi-braunschweig/SORMAS-Project pull request #8736
Opened 2022-04-06 15:04 UTC by mk-sgent

2022-04-06 15:11 UTC, mk-sgent commented
![SORQA-150](https://user-images.githubusercontent.com/97879405/162007578-ba970827-6786-4527-b0ec-774e1eb13b48.PNG)


**First**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/686/allure/#suites/8c58061b2ed2b35ae02eed396f7f38ec/ed26bc78fde5d44c/

2022-04-08 07:24 UTC, rdutu-vg requested changes

2022-04-08 07:24 UTC, rdutu-vg commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/contacts/EditContactPage.java
> +  public static final By DISEASE_VALUE = By.xpath("//div[text()='COVID-19 ']");
we cannot create locators based on specific data, because this is not reusable. Also, it wouldn't be stable if you have this value in other places.

2022-04-08 07:24 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/contacts/EditContactSteps.java
> +          //          webDriverHelpers.clickOnWebElementBySelector(APPLY_FILTERS_BUTTON);
remove if no longer used

2022-04-13 10:10 UTC, merged