Change 4461 replace hard coded user roles with fully configurable user roles
hzi-braunschweig/SORMAS-Project pull request #8759
Opened 2022-04-08 07:52 UTC by ChristopherRiedel

Fixes #4461 

**Don't merge this PR**

2022-05-09 13:54 UTC, MartinWahnschaffe requested changes
I have started by reviewing the sormas-api project.
There are multiple usages of UserRoleDto that need to be replaced by UserRoleReferenceDto.

2022-05-09 13:54 UTC, MartinWahnschaffe commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
> +	public void setReportingUserRoles(Set<UserRoleDto> roles) {
Use UserRoleReferenceDto

2022-05-09 13:54 UTC, MartinWahnschaffe commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventCriteria.java
> +	private UserRoleDto reportingUserRole;
Use UserRoleReferenceDto

2022-05-09 13:54 UTC, MartinWahnschaffe commented on sormas-api/src/main/resources/enum.properties
> +# DefaultUserRole
Move up based on alphabetical ordering of this file

2022-05-09 15:16 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserFacadeEjb.java
> +		if (userRoleFacade.hasUserRight(
Use currentUserService.hasUserRight

2022-05-09 15:20 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRightsFacadeEjb.java
> +		for (DefaultUserRole userRole : DefaultUserRole.values()) {
Use roles from userRoleRights instead

2022-05-09 15:20 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserRightsFacadeEjb.java
> +		for (DefaultUserRole userRole : DefaultUserRole.values()) {
Use roles from userRoleRights instead

2022-05-09 15:23 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
> +			Join<User, DefaultUserRole> joinRoles = from.join(User.USER_ROLES, JoinType.LEFT);
Should be UserRole

2022-05-09 15:24 UTC, MartinWahnschaffe commented on sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java
> +		return getCurrentUser().getUserRoles().stream().flatMap(role -> role.getUserRights().stream()).collect(Collectors.toSet()).contains(right);
Replace with currentUserService.hasRight

2022-05-10 09:04 UTC, MartinWahnschaffe requested changes
A few changes needed for tests in backend and ui.

Final part missing of the code review is the sormas-app. Will take care of that later today.

2022-05-10 09:04 UTC, MartinWahnschaffe commented on sormas-ui/src/test/java/de/symeda/sormas/ui/TestDataCreator.java
> +	public Map<DefaultUserRole, UserRoleReferenceDto> getUserRoleDtoMap() {
Replace with getUserRoleReference(DefaultUserRole) (see backend tests)

2022-05-10 14:44 UTC, MartinWahnschaffe requested changes

2022-05-19 13:03 UTC, MateStrysewske requested changes

2022-05-19 13:03 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/UserProvider.java
> +	private Boolean hasAssociatedOfficer;
See above

2022-05-20 10:45 UTC, MateStrysewske requested changes

2022-05-20 10:45 UTC, MateStrysewske commented on sormas-api/src/main/resources/captions.properties
>  UserRole.hasAssociatedOfficer=Has associated officer
Translation has to be adjusted here (= "Has associated district user")

2022-05-20 10:45 UTC, MateStrysewske commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +ALTER TABLE userroles ADD COLUMN hasassociateddistrcituser boolean default false;
Typo

2022-05-20 10:45 UTC, MateStrysewske commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +ALTER TABLE userroles_history ADD COLUMN hasassociateddistrcituser boolean default false;
Typo

2022-05-20 10:45 UTC, MateStrysewske commented on sormas-backend/src/test/java/de/symeda/sormas/backend/TestDataCreator.java
> +			userRoleDto.setHasAssociatedDistrictUser(defaultUserRole.hasAssociatedOfficer());
Looks like the setter in `DefaultUserRole` has not been renamed

2022-05-20 10:45 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/UserProvider.java
>  	public boolean hasAssociatedOfficer() {
Rename this method as well

2022-05-20 10:46 UTC, MateStrysewske requested changes
Tests are failing because some renamings also need to be reflected in the mobile app

2022-05-23 07:51 UTC, ChristopherRiedel commented
> Tests are failing because some renamings also need to be reflected in the mobile app

should be fixed

2022-05-23 11:31 UTC, MateStrysewske approved these changes

2022-05-23 11:31 UTC, merged