Qu auto/sorqa 171 Bulk mode for Activate/deactivate user accounts[SORDEV-5964]
hzi-braunschweig/SORMAS-Project pull request #8793
Opened 2022-04-11 16:04 UTC by mk-sgent

2022-04-12 07:51 UTC, mk-sgent commented
![SORQA-171](https://user-images.githubusercontent.com/97879405/162909271-f109193c-512d-4451-a630-03dd509c4f35.PNG)

Jenkins jobs:
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/725/allure/#suites/bd663fa712ccafbe2d65d1dd364e02f0/a13137754208214a/

2022-04-18 07:40 UTC, rdutu-vg requested changes

2022-04-18 07:40 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java
> +            String userDataPartial = user.getUserName().substring(0, 17);
use the full user uuid, is more stable and precise

2022-04-18 07:40 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java
> +  private static Integer amountOfRecords;
declare it as int

2022-04-18 07:40 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java
> +    When("I Count amount of user", () -> {});
why is this method empty?

2022-04-18 07:40 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/users/CreateNewUserSteps.java
> +              amountOfRecords, optionsRecords, "Not all Active fields value are changed");
you need to add also softly.assertAll to have the check validated

2022-04-18 07:40 UTC, rdutu-vg commented
address pr comments and re-run the test

2022-04-19 12:29 UTC, rdutu-vg approved these changes

2022-04-19 12:29 UTC, merged