Added scenario [SORDEV-5967] "Add evidence fields for event clusters"…
hzi-braunschweig/SORMAS-Project pull request #8808
Opened 2022-04-13 07:44 UTC by mk-sgent

2022-04-13 07:54 UTC, jp-sgent commented on sormas-e2e-tests/src/main/java/org/sormas/e2etests/pages/application/events/EditEventPage.java
> +      By.xpath("//label[text()='Fall-Kontroll-Studie']");
I suggest adding a "_DE" suffix to the names of german-specific variables.

2022-04-13 07:54 UTC, jp-sgent commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
> +        "I thick all options for Study on Epidemiological evidence for De version",
If by "thick" you mean marking a checkbox, then it's a typo (should be "tick", not "thick").

2022-04-13 08:32 UTC, jp-sgent approved these changes

2022-04-13 08:37 UTC, mk-sgent commented
![SORQA-185](https://user-images.githubusercontent.com/97879405/163135570-004e247c-9270-408a-a90d-58c45a2c91c2.PNG)

Jenkins jobs:
**First**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/735/allure/
**Second**
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/736/allure/

2022-04-13 12:12 UTC, pk-sgent approved these changes

2022-04-18 08:35 UTC, rdutu-vg requested changes

2022-04-18 08:35 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
> +        "I select {} option from Primary Mode Of Transmission Combobox on edit Event page",
should {string}

2022-04-18 08:35 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
> +    And I click on SAVE button in edit event form
test is not completed, we select all options here, but we don't also check the test case checks after.

![image](https://user-images.githubusercontent.com/83643843/163781487-977d625d-f9ab-4b45-a613-b8f3d29a434f.png)

2022-04-29 11:55 UTC, rdutu-vg approved these changes

2022-05-04 12:41 UTC, merged