SORQA-272
hzi-braunschweig/SORMAS-Project pull request #9413
Opened 2022-06-02 20:05 UTC by pk-sgent

SORQA-272

2022-06-11 12:26 UTC, pk-sgent commented
https://github.com/hzi-braunschweig/SORMAS-Project/pull/9413

2022-06-11 13:08 UTC, pk-sgent commented
![image](https://user-images.githubusercontent.com/96249076/173189328-5bb4fb1e-3503-471e-a692-3b07c9d956fe.png)

2022-06-13 08:19 UTC, rdutu-vg requested changes

2022-06-13 08:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditCaseSteps.java
> +          softly.assertFalse(
add assert message

2022-06-13 08:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EditContactsSteps.java
> +          softly.assertFalse(
add assert message

2022-06-13 08:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java
> +              webDriverHelpers.checkIfElementExistsInCombobox(TYPE_OF_ACTIVITY_COMBOBOX, option));
same

2022-06-13 08:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/cases/EpidemiologicalDataCaseSteps.java
> +          softly.assertFalse(webDriverHelpers.isElementVisibleWithTimeout(ANIMAL_CONTACT_LABEL, 1));
same

2022-06-13 08:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/samples/CreateNewSampleSteps.java
> +          softly.assertFalse(
same

2022-06-22 10:20 UTC, pk-sgent commented
after rebase + fixing 
![image](https://user-images.githubusercontent.com/96249076/175006046-65c6678e-0fbc-490a-9fa8-d37063f11cf8.png)

2022-06-22 13:27 UTC, merged