SORQA-307
hzi-braunschweig/SORMAS-Project pull request #9417
Opened 2022-06-03 12:28 UTC by lb-sgent

![image](https://user-images.githubusercontent.com/105343291/171853516-04c49dc7-4422-4f96-b398-f89e8fc1e08f.png)

2022-06-03 12:42 UTC, mp-sgent requested changes

2022-06-03 12:42 UTC, mp-sgent commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java
> +          webDriverHelpers.clickOnWebElementBySelector(EVENT_TAB);
Navigation to event tab after event creation should be already available as a separate step, so I suggest removing it from this step and using already defined for that action.

2022-06-03 12:42 UTC, mp-sgent commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/CreateNewEventSteps.java
> +          Assert.assertTrue(
This assert should be treated as a separate step and be placed in EditEventSteps cause action that it performs in in that directory.

2022-06-03 12:42 UTC, mp-sgent commented on sormas-e2e-tests/src/test/resources/features/sanity/web/Event.feature
> +    And I create a new event with event identification source UNKNOWN
Test suite can be paramatrized with that event identification source value.

2022-06-03 15:35 UTC, rdutu-vg approved these changes

2022-06-07 10:58 UTC, lb-sgent commented
![image](https://user-images.githubusercontent.com/105343291/172363461-c2c47f37-f57e-4ddd-92eb-4a7564932b31.png)

2022-06-21 12:56 UTC, hms-sgent approved these changes

2022-06-22 08:50 UTC, lb-sgent commented
![image](https://user-images.githubusercontent.com/105343291/174986627-56013c80-c117-4863-8fff-b11c5ede65ef.png)
Conflicts resolved

2022-06-22 09:11 UTC, pk-sgent approved these changes

2022-06-22 13:27 UTC, rdutu-vg approved these changes

2022-06-22 13:28 UTC, merged