#8974 - Group aggregated reporting data (mSERS) by jurisdiction and e…
hzi-braunschweig/SORMAS-Project pull request #9431
Opened 2022-06-07 07:26 UTC by sergiupacurariu

…pi week

Fixes #8974

2022-06-07 08:16 UTC, BarnaBartha approved these changes

2022-06-07 11:34 UTC, MateStrysewske requested changes
- Grouping dropdown content does not have proper captions
- Default selections for epi year and week have been removed, should be added back (i.e. display the current week by default)
- Move the "Apply filters" button next to the time filters
- If I understood the issue description correctly, we need to show one line per epi week per disease; this is currently not the case

2022-06-09 13:36 UTC, MateStrysewske requested changes
0-groupings are not working correctly right now. If I display them e.g. for epi week 24, the "epi week" column shows "0" for the diseases that have no reports there, but it should still display 24. Also, we need to show one row per disease per epi week that is displayed (i.e. when filtering from epi week 18 to 24, we need to show at least 7 rows per disease), potentially more if there are age and jurisdiction groupings.

2022-06-10 12:18 UTC, MateStrysewske approved these changes

2022-06-10 12:19 UTC, MateStrysewske requested changes
There are two failing tests - once they're running through, this PR can be merged. :)

2022-06-10 13:56 UTC, merged