#8980 physician report processing
hzi-braunschweig/SORMAS-Project pull request #9441
Opened 2022-06-07 12:32 UTC by leventegal-she

Fixes #8980

2022-06-08 11:59 UTC, vidi42 requested changes

2022-06-08 11:59 UTC, vidi42 commented on sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/labmessage/processing/AbstractLabMessageProcessingFlow.java
> +		List<SimilarEventParticipantDto> similarEventParticipants = getSimilarEventParticipants(externalMessage, personRef);
Would be nice to use the same order for the parameters as the methods above. so 1st have the `personRef`, then the `externalMessage`

2022-06-08 11:59 UTC, vidi42 commented on sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/physicianreport/AbstractPhysicianReportProcessingFlow.java
> +								convertSamePersonContactsAndEventparticipants(c.getData()).thenCompose((ignored) -> CompletableFuture.completedFuture(c)))
```suggestion
								convertSamePersonContactsAndEventParticipants(c.getData()).thenCompose((ignored) -> CompletableFuture.completedFuture(c)))
```
Just changed the capitalization for `convertSamePersonContactsAndEventParticipants`

2022-06-09 07:04 UTC, ChristopherRiedel requested changes
Please rename every occurence of "physicianreport" to "physician**s**report".

2022-06-09 10:09 UTC, ChristopherRiedel approved these changes

2022-06-09 10:29 UTC, merged