Test for immunization data in Edit Person Directory
hzi-braunschweig/SORMAS-Project pull request #9461
Opened 2022-06-10 09:36 UTC by mp-sgent

2022-06-10 09:44 UTC, mp-sgent commented
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1242/

2022-06-10 09:51 UTC, pk-sgent approved these changes

2022-06-10 10:30 UTC, hms-sgent approved these changes

2022-06-13 08:24 UTC, rdutu-vg requested changes

2022-06-13 08:24 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/persons/EditPersonSteps.java
> +          softly.assertAll();
please add failures messages to asserts

2022-06-16 07:57 UTC, rdutu-vg approved these changes

2022-06-21 14:02 UTC, rdutu-vg approved these changes

2022-06-21 14:02 UTC, merged