#9274-notice survnet about cases/events archivation/dearchivation
hzi-braunschweig/SORMAS-Project pull request #9542
Opened 2022-06-17 14:00 UTC by carina29

…d/dearchived

Fixes #9274

2022-06-22 11:24 UTC, leventegal-she requested changes

2022-06-22 11:24 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ArchivingController.java
> +                    callback.run();
please reformat the code

2022-06-22 11:24 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java
> +			CriteriaBuilderHelper.and(cb, entityUuidsFilter, associatedObjectJoin.get(AbstractDomainObject.ID).in(survToolShareSubQuery).not());
please move the `.not()` before `.in(survToolShareSubQuery)`. it's confusing

2022-06-22 11:24 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +	public void setArchiveInExternalSurveillanceToolForEntity(String entityUuid, boolean archived) throws ExternalSurveillanceToolException {
these methods should be moved to the service

2022-06-22 11:24 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +	public boolean hasExternalId(String entityUuid) {
I think this can be removed

2022-06-22 11:24 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
> +	public void setArchiveInExternalSurveillanceToolForEntity(String eventUuid, boolean archived) throws ExternalSurveillanceToolException {
these methods should be moved to the service

2022-06-23 10:04 UTC, carina29 commented
The requested changes were committed.

2022-06-23 10:31 UTC, leventegal-she requested changes
PLease reformat the changed classes and remove unused imports and fields

2022-06-23 10:31 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +    @EJB
formatting issue

2022-06-23 10:31 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java
> +	private EventService eventService;
seems it's not used so it can be removed, pleas also remove unused imports

2022-06-23 10:31 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java
> +    private EventFacadeEjb.EventFacadeEjbLocal eventFacade;
formatting issue

2022-06-23 10:31 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java
> +	public void sendCases(List<String> caseUuids, boolean archived) throws ExternalSurveillanceToolException {
formatting issue

2022-06-27 08:15 UTC, leventegal-she approved these changes

2022-06-27 12:47 UTC, merged