SORQA-311
hzi-braunschweig/SORMAS-Project pull request #9761
Opened 2022-07-07 10:01 UTC by lb-sgent

<img width="423" alt="image" src="https://user-images.githubusercontent.com/105343291/177747666-583eeab6-7d78-425d-8c06-1ca7b8faab5e.png">

2022-07-07 10:05 UTC, hms-sgent approved these changes

2022-07-07 15:05 UTC, rdutu-vg requested changes

2022-07-07 15:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
> +          Assert.assertEquals(archiveDearchive, "De-Archive");
add also assert message

2022-07-07 15:05 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EventDirectorySteps.java
> +          Assert.assertFalse(
assert message

2022-07-08 09:22 UTC, lb-sgent commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/events/EditEventSteps.java
> +          TimeUnit.SECONDS.sleep(3);
Sleep changed to 1s.
It need to be used for page reload after archiving event.

2022-07-08 15:47 UTC, rdutu-vg approved these changes

2022-07-08 15:47 UTC, merged