qu-auto/SORQA-367 Automatize "Immunizations III: Immunization list for cases, contacts and event participants [5]"
hzi-braunschweig/SORMAS-Project pull request #9774
Opened 2022-07-07 15:26 UTC by hms-sgent

Fixes #

2022-07-08 06:38 UTC, hms-sgent commented
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/1445/
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/1446/
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/1448/

2022-07-08 06:39 UTC, hms-sgent commented
![image](https://user-images.githubusercontent.com/105210214/177932056-0751e739-548e-427a-a574-8923ab3bab10.png)

2022-07-11 14:59 UTC, rdutu-vg requested changes

2022-07-12 11:32 UTC, hms-sgent commented on sormas-e2e-tests/src/test/resources/features/sanity/web/Immunization.feature
> +  Scenario: Immunization III: List for cases, contacts and event participants
done

2022-07-12 11:32 UTC, hms-sgent commented
https://jenkins.sormas.netzlink.com/job/sormas-RunE2eTests-branch/1473/

2022-07-12 15:35 UTC, rdutu-vg approved these changes

2022-07-12 15:35 UTC, merged