Automatize "[4502] Event - follow-up of actions: attach documents at the level of the action carried out"
hzi-braunschweig/SORMAS-Project pull request #9939
Opened 2022-07-22 14:37 UTC by mp-sgent

2022-07-22 14:39 UTC, mp-sgent commented
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1534/allure/#

2022-07-25 09:19 UTC, rdutu-vg requested changes

2022-07-25 09:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/EditActionSteps.java
> +          TimeUnit.SECONDS.sleep(2);
why this sleep?

2022-07-25 09:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/EditActionSteps.java
> +          TimeUnit.SECONDS.sleep(2); // wait for upload file
the file might be autoamatically uploaded, not sure if sleep is needed

2022-07-25 09:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/EditActionSteps.java
> +          softly.assertTrue(Files.exists(path));
assert message missing

2022-07-25 09:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/EditActionSteps.java
> +          softly.assertTrue(Files.exists(path));
assertHelpers.assertWithPoll(
              () ->
                  Assert.assertTrue(
                      Files.exists(path),
                      dictionaryName + " wasn't downloaded: " + path.toAbsolutePath()),
              30); 

And you can use this approach to wait after file to be downloaded and check it

2022-07-25 09:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/EditActionSteps.java
> +          TimeUnit.SECONDS.sleep(3); // wait for download
remove this

2022-07-25 09:19 UTC, rdutu-vg commented on sormas-e2e-tests/src/test/java/org/sormas/e2etests/steps/web/application/actions/EditActionSteps.java
> +          TimeUnit.SECONDS.sleep(5); // wait for system reaction
remove this as long as we have the spinner loading handle

2022-07-27 08:36 UTC, rdutu-vg approved these changes

2022-07-27 08:36 UTC, merged