[#9838] contact editable for not handed over case
hzi-braunschweig/SORMAS-Project pull request #9947
Opened 2022-07-25 14:57 UTC by JonasCir

Fixes #9838

2022-07-28 10:54 UTC, leventegal-she requested changes

2022-07-28 13:06 UTC, JonasCir commented
@leventegal-she i fixed the method naming, but I'm still uncertain about your comment on the archiving...

2022-08-02 07:57 UTC, JonasCir commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +		// we allow CaseContactViewEdit independently of the ownership handover
@leventegal-she talked to both and we settled on jurisdiction check and archive check in super.

2022-08-02 09:24 UTC, leventegal-she approved these changes

2022-08-02 09:25 UTC, merged